### ISSUE TITLE
Change the Constructor Name of Sequential Colimits

### ISSUE THREAD

**Issue by kangrongji** [agda/cubical#1046]
When using [sequential colimits from the library](https://github.com/agda/cubical/blob/master/Cubical/HITs/SequentialColimit/Base.agda), the constructor `inl` can be hard to align with `push` during pattern patching, etc. So it doesn't look good. Renaming it to `incl` and maybe changing the field name `space` to `obj` would improve alignment and give a more category-theory-inspired feel. If you all agree, I could make a PR very soon.

**Comment by felixwellen** [comment]
Not a user of sequential colimits (yet), but this looks like an improvement to me.
What do you think about the name ```Lim→```? 
I consistently forger the traditional math notation it resembles over the years, but maybe that's just me. It is also a lot shorter than ```SeqColim```.

**Comment by kangrongji** [comment]
Yeah... I think `Lim→` looks a bit weird. There is no hurt to use `SeqColim` instead. I could do all these changes.
