### ISSUE TITLE
Some Files are never checked

### ISSUE THREAD

**Issue by felixwellen** [agda/cubical#1054]
I noticed that 
```
Cubical/Experiments/CohomologyGroups.agda
```
is outdated - some imports don't exist anymore. Looking at CI logs, it seems to be never checked.

**Comment by felixwellen** [comment]
Same:
```
Cubical/Experiments/ZCohomologyOld/MayerVietorisUnreduced.agda
```

**Comment by felixwellen** [comment]
Ah - I get it now. There is a manually edited ```Everything.agda``` and these files and a couple of others are excluded, because the don't check anymore. Do we really want to keep these files?

**Comment by mortberg** [comment]
> Ah - I get it now. There is a manually edited `Everything.agda` and these files and a couple of others are excluded, because the don't check anymore. Do we really want to keep these files?

Not sure about these particular files... What does @aljungstrom think as he wrote them?

At some point we discussed deleting the whole Experiments folder as it doesn't really make sense in a library

**Comment by aljungstrom** [comment]
I'm fine with this disappearing. I don't see when we'd use it and I still have it backed up on some old branches.

**Comment by mortberg** [comment]
> I'm fine with this disappearing. I don't see when we'd use it and I still have it backed up on some old branches.

Ok, feel free to make a PR deleting old files @felixwellen

**Comment by felixwellen** [comment]
Ok - I will. Thanks!
I will be back with a PR at some point -> closing this issue.
