### ISSUE TITLE
Algebraic geometry

### ISSUE THREAD

**Issue by mzeuner** [agda/cubical#1095]
By now, the library has quite a bit of stuff on (constructive) algebraic geometry, but it is spread out.
The stuff based on the lattice theoretic approach of [Coquand, Lombardy and Schuster](https://link.springer.com/article/10.1007/s10472-009-9160-7) is in `Cubical.Algebra.ZariskiLattice`, whereas the functor of points approach is developed in `Cubical.Categories.Instances.ZFunctors`.

I would suggest to make a folder `Cubical.AlgebraicGeometry` that itself contains to folders for the two approaches currently (partly) formalized and move everything algebraic geometry related there.

Does that sound like a reasonable idea?

**Comment by mortberg** [comment]
Yes, that would be great

**Comment by mortberg** [comment]
Has this been fixed now?
