### ISSUE TITLE
Figure out why the CommRingSolver doesn't work in this case

### ISSUE THREAD

**Issue by felixwellen** [agda/cubical#1097]
When looking at the goal type in the case below, it is actually something the CommRingSolver should be able to solve. But when trying to solve this, the solver actually gets meta-variables it cannot use.

![comment](https://github.com/agda/cubical/pull/1093#discussion_r1476059816)
![image](https://github.com/agda/cubical/assets/22154668/4094980a-84b7-4051-b575-aa489aac52d4)

**Comment by felixwellen** [comment]
Here is another case, which might be related (or not):

![image](https://github.com/agda/cubical/assets/22154668/82a968f6-cc15-4125-a70a-6de2503a4398)

**Comment by felixwellen** [comment]
> When looking at the goal type in the case below, it is actually something the CommRingSolver should be able to solve. But when trying to solve this, the solver actually gets meta-variables it cannot use.
> 
> ![image](https://private-user-images.githubusercontent.com/22154668/301915277-4094980a-84b7-4051-b575-aa489aac52d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDIzMDAsIm5iZiI6MTcwNzA0MjAwMCwicGF0aCI6Ii8yMjE1NDY2OC8zMDE5MTUyNzctNDA5NDk4MGEtODRiNy00MDUxLWI1NzUtYWE0ODlhYWM1MmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDEwMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllN2I2YjMzMjBmMGRkOGZhZDkxMDM3NTg2NTM0YTMzYmZmOGEyY2I0OTJhMGFiYzBiNmNhZDdjMTU4NGVhODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8WFHbsjGOkFmfk7glnlbkduDWrm-QU3YHo6P6c_EfFc)

It seems like the marco gets only the type in the message below:
![image](https://github.com/agda/cubical/assets/22154668/34223579-fa03-4d89-b197-e01b0d7d4eaf)
So the task is to figure out how to use the reflection interface to tell agda to get more information on the type of the hole.

**Comment by ncfavier** [comment]
Links are more useful than screenshots:
https://github.com/agda/cubical/pull/1093#discussion_r1476059816
https://github.com/agda/cubical/pull/1093#discussion_r1476066747

It looks like adding `wait-for-type goal` in `solve!-macro` does it.

**Comment by felixwellen** [comment]
Yes - it does! Many thanks!

**Comment by felixwellen** [comment]
#1093 is merged and solves both problems -> closing.
