### ISSUE TITLE
Clean up and make Cubical.Foundations.Logic universe polymorphic

### ISSUE THREAD

**Issue by mortberg** [agda/cubical#111]
The file https://github.com/agda/cubical/blob/master/Cubical/Foundations/Logic.agda should be made universe polymorphic and Ω should be removed in favour of hProp

**Comment by L-TChen** [comment]
I almost have finished this issue. Since I need this to have a recursion from free semilattices to types, so I proved a few more than I need. I will create a PR when it is ready. Hope you don't mind. 

 https://github.com/L-TChen/cubical/blob/logic-properties/Cubical/Foundations/Logic.agda

**Comment by Saizan** [comment]
Fixed by #113
