### ISSUE TITLE
Check whitespace in Makefile

### ISSUE THREAD

**Issue by L-TChen** [agda/cubical#114]
There is a [tool](https://github.com/agda/agda/blob/master/src/fix-agda-whitespace/FixWhitespace.hs) in Agda to fix the whitespace issue.  The following is the explanation from the tool

> Background: Agda was reported to fail to compile on Windows because a file did not end with a newline character (Agda uses -Werror).

If this is still an issue, then this check should be included in the Makefile so that Travis can check it as well. 

Unfortunately, I will be unavailable for a few week, so I won't be able to make a PR on this.

**Comment by anqurvanillapy** [comment]
This tool has no corresponding `stack` setup files and is forced to use in `cubical/GUmakefile`.  I `make`-d this repo by using `make check`.  Maybe the order of build dependencies should be rearranged to make `test` optional?  Moreover the stack install instructions now seem to be inconsistent with these.

**Comment by Saizan** [comment]
@anqurvanillapy I agree that `make` should just typecheck:

51c71580f49f51b606d7cbc20aa7a8cd4940d5cf
