### ISSUE TITLE
Adding modalities for truncations and other things

### ISSUE THREAD

**Issue by Alizter** [agda/cubical#115]
One of the things I like about the HoTT-coq library is that truncations are defined as modalities, then many results about truncations come from their more general counter-parts for modalities. it will be a bit of a long project to write a modalities library for cubical agda but I think it could be done. The advantage would be that many results such as Blakers-Massey will end up holding in much greater generality, I have been trying to prove GBMT for a while in HoTT-coq now but there are many technical small lemmas that are needed. It would be very interesting to see if cubical can help.

Another thing I would be interested to see is Bruneries 3x3 lemma in cubical. Showing that pushouts commute with pushouts on a 3x3 square of span rows and columns. This has been proven in the agda library but I struggled to prove it in coq.

**Comment by mortberg** [comment]
Yes, I agree that all of these things would be nice to have in Cubical Agda. I'm very optimistic that the 3x3 lemma will be easier to prove cubically because of the additional computation rules.

Regarding modalities I don't have much to say except that I know that my goto guy for these topics, @felixwellen , is working on a formalization of localizations now. Maybe he wants to weigh in about adding some theory about general modalities to the library.

**Comment by felixwellen** [comment]
If I want to show in the end, that some localizations are modalities, I have to add at least a definition anyway. So we could also add that now, if someone wants to work with it. Where would it go? The localization should be in HITs I guess, but I'm clueless if modalities should be there as well. Or in Foundations. Or in a new Modalities directory.

**Comment by mortberg** [comment]
Let's make a new Modalities directory for now

**Comment by felixwellen** [comment]
Here is how I would define modalities (adapted from HoTT-Agda):

https://github.com/felixwellen/cubical/blob/modalities/Cubical/Modalities/Modality.agda

I think it is the most easy-to-use definition.

**Comment by mortberg** [comment]
> Another thing I would be interested to see is Bruneries 3x3 lemma in cubical. Showing that pushouts commute with pushouts on a 3x3 square of span rows and columns. This has been proven in the agda library but I struggled to prove it in coq.

As you might have seen @loic-p did the 3x3 lemma now: https://github.com/agda/cubical/pull/123

It seems substantially shorter than https://github.com/HoTT/HoTT-Agda/tree/master/theorems/homotopy/3x3 , but I don't know if everything in that folder is just for the proof of this or not...

**Comment by Alizter** [comment]
@mortberg AFAIK Brunerie's thesis is the only account of the proof and the Agda proof is pretty much the same as the one he describes. This means that the new cubical proof is an improvement over this one.
