### ISSUE TITLE
Cubical.Data.Rational: define operations and equivalence with HoTT def.

### ISSUE THREAD

**Issue by Saizan** [agda/cubical#116]
Right now ```Cubical.Data.Rational``` only contains the datatype.

Arithmetic is there to be implemented!

The Book defines rationals as the set quotient ```Z x N / ~``` where 
```(a, b) ~ (c, d) iff a(d + 1) = c(b + 1)```
and it would be good to provide an equivalence.

**Comment by mortberg** [comment]
Closing this as it's superseded by https://github.com/agda/cubical/issues/404
