### ISSUE TITLE
Error running Primitives.agda "Not a valid pattern"

### ISSUE THREAD

**Issue by mwand** [agda/cubical#13]
When I run Primitives.agda, I get:

```
C:\Users\wand\Dropbox\Work\Research\Cubicaltt 2018\cubical-agda\Cubical\Core\Primitives.agda:86,10: Not a valid pattern: i = i0
=<ERROR>
 Set
  sys i (i = i1) = Set
```

I am running Agda version 2.5.4.1 

What am I doing wrong?

**Comment by potato4444** [comment]
This library is designed to work with the development version of Agda (that will become Agda 2.6.0). It uses features that are not available in older versions of Agda.

**Comment by mwand** [comment]
Thanks!  I will try again with the development version.

**Comment by ice1000** [comment]
Should this be closed?
