### ISSUE TITLE
Cubical.Core.Glue is broken

### ISSUE THREAD

**Issue by L-TChen** [agda/cubical#130]
After the commit https://github.com/agda/agda/commit/13d516f20d5cdf88e35349a2d8ddc52e1c5c2dde, `Cubical.Core.Glue` isn't working anymore. Here is the error message: 

```agda
unglueIsEquiv A (~ i0 ∨ i0)
(λ { (i0 = i0) → A , idEquiv A ; (i0 = i1) → w })
!= idIsEquiv A of type isEquiv (unglue (~ i0 ∨ i0))
when checking that the expression
λ i →
  let f : PartialP (~ i ∨ i) (λ x → Σ-syntax (Set ℓ) λ T → T ≃ A)
      f = λ { (i = i0) → A , idEquiv A ; (i = i1) → w }
  in Glue A f , unglueEquiv _ _ f
has type (A , idEquiv A) ≡ w
```

**Comment by Saizan** [comment]
You should pull this commit:

https://github.com/agda/cubical/commit/c318c8d058cd9f0b288f8a57bd29744a4874a754

**Comment by L-TChen** [comment]
Oops, my silly mistake. I happened to switch to someone else's branch to check their problem.
