### ISSUE TITLE
Define truncations as nullification modalities

### ISSUE THREAD

**Issue by Alizter** [agda/cubical#138]
as discussed in #134 

I suppose this issue also includes defining localization and finally showing that the two definitions of truncation are the same.

**Comment by felixwellen** [comment]
I did some work along the lines of the Rijke,Shulman,Spitters-article on modalities towards defining localizations:

https://github.com/felixwellen/cubical/blob/localization/Cubical/Modalities/Localization.agda

I won't work too much on it, so if you(/anyone) want to pick it up, please do and let me know.
