### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by Alizter** [agda/cubical#143]
We have quite a few stale branches in this repo at the moment. Since most of these have been merged or abandoned, can we delete them?

**Comment by Saizan** [comment]
Yeah, I guess when we merge a branch we should delete it.

Github even offers a nice button for it if you merge a PR from the website.

**Comment by Saizan** [comment]
I went and deleted all branches from a merged PR.

@mortberg there are 3 branches without a PR left, can you check whether they are still useful to keep?

https://github.com/agda/cubical/branches

**Comment by Alizter** [comment]
I'll close this issue for now, we can open it again when it builds up.

**Comment by mortberg** [comment]
> I went and deleted all branches from a merged PR.
> 
> @mortberg there are 3 branches without a PR left, can you check whether they are still useful to keep?
> 
> https://github.com/agda/cubical/branches

I removed all but one. If someone finds a slick proof of the hole on the remaining branch then it might be worth merging.
