### ISSUE TITLE
Help with reversing an application of `sym` to `ua` and `isoToEquiv`

### ISSUE THREAD

**Issue by wvhulle** [agda/cubical#146]
For my master thesis about cubical type theory, I am proving a kind of structure invariance principle for magmas with this library.

At some point in the proof I have the following given:
-  A bijection between types: `f : ℕ → ℕ₀ `
-  The isomorphism constructed with `f`: `fIso : Iso ℕ ℕ₀`
-  A function that gives the inverse isomorphism of an isomorphism: `invIso : Iso A B → Iso B A`

Now, I would like to prove that
`sym (ua (isoToEquiv fIso)) ≡ ua (isoToEquiv (invIso fIso))`
Is this a valid theorem in HoTT? Are there built-in functions in this library that may help in the proof?

**Comment by Alizter** [comment]
Forgetting about isomorphisms, what you want to prove is that symmetry of equivalences and symmetry of paths are invariant under univalence. You can find this lemma straight after the univalence axiom is introduced in 2.10.3 in the HoTT book.

For cubical type theory, this should be even easier.

**Comment by wvhulle** [comment]
Thanks, @Alizter ! You probably mean `ua(f)^{−1} = ua(f^{−1})`? I will try to implement this in cubical type theory.

**Comment by Saizan** [comment]
@wvhulle It should be fairly direct from ```EquivJ```

https://github.com/agda/cubical/blob/33359763ec0c33daa2fe42bc47d60b5e1cf15762/Cubical/Foundations/Univalence.agda#L95

**Comment by mortberg** [comment]
I proved this now: https://github.com/agda/cubical/pull/147

**Comment by wvhulle** [comment]
@mortberg , that's very friendly! :) This was my solution for my particular problem:
```agda
baseIndLemma : (A : Type ℓ-zero) → (λ i → ua (idEquiv A) (~ i)) ≡ ua (invEquiv (idEquiv A))
baseIndLemma A = 
  sym ( ua (idEquiv A) ) ≡⟨ uaIdEquiv ⟩
  sym refl ≡⟨ refl ⟩
  refl ≡⟨ sym uaIdEquiv ⟩
  ua (idEquiv A) ≡⟨ cong ua (equivEq (idEquiv A) (invEquiv (idEquiv A)) refl) ⟩
  ua (invEquiv (idEquiv A)) ∎

myUaInvEquiv : sym (ua fEquiv) ≡ (ua (invEquiv fEquiv))
myUaInvEquiv = EquivJ
  (λ _ _ e → sym (ua e) ≡ ua (invEquiv e)) (λ A → baseIndLemma A) ℕ₀ ℕ fEquiv 
```
Unfortunately, normalizing the endresult of the rest of my code (a transport of some proof) results in a memory leak, but i should probably make a separate issue for that.
