### ISSUE TITLE
One more HIT Int

### ISSUE THREAD

**Issue by phadej** [agda/cubical#150]
I was playing with Cubical Agda and got https://gist.github.com/phadej/527ad34e3bed28e5ea3e8cf9d9a2cb79 to work.

```agda
data ℤ : Set where
  zero : ℤ
  succ : ℤ → ℤ
  pred : ℤ → ℤ

  succpred : ∀ z → succ (pred z) ≡ z
  predsucc : ∀ z → pred (succ z) ≡ z

  trunc : isSet ℤ

...

Int≡ℤ : Int ≡ ℤ
Int≡ℤ = isoToPath (iso Int→ℤ ℤ→Int ℤ→Int→ℤ Int→ℤ→Int)
```

Should it be included in this library: it demonstrates the truncation problem as mentioned in http://www.cs.nott.ac.uk/~psztxa/talks/bonn18.pdf

**Comment by m-yac** [comment]
This is inspiring me to finish a port of redprl's [biinv-int](https://github.com/RedPRL/redtt/blob/master/library/cool/biinv-int.red) that I started last year (https://github.com/m-yac/cubical/tree/biinv-int). It adds the following HIT equivalent to Int:
```agda
data BiInvInt : Type₀ where
  zero : BiInvInt
  suc : BiInvInt -> BiInvInt
  -- suc is a bi-invertible equivalence:
  predr : BiInvInt -> BiInvInt
  suc-predr : ∀ z -> suc (predr z) ≡ z
  predl : BiInvInt -> BiInvInt
  predl-suc : ∀ z -> predl (suc z) ≡ z
```
A close cousin of this type is mentioned* in the linked slides as an example of the other way to solve the 'truncation problem' -- adding coherences. I think these twos HITs would complement one another well.

\* What Thorsten actually states is hard to work with, I tried and failed to prove it equivalent to Int and it seems others have too: https://github.com/agda/cubical/blob/master/Cubical/Experiments/HInt.agda

**Comment by mortberg** [comment]
It would be great to have both the truncated and untruncated (based on biinv-int) versions in the library. So please make PRs.

The version from Thorsten's slides is indeed a nightmare to work with and I only pushed what worked to the HInt file. I tried many different approaches to filling those holes, but it always led straight to coherence hell.

**Comment by phadej** [comment]
@mortberg Should I put my variant into `Cubical.HITs.IntTrunc` ?

**Comment by mortberg** [comment]
That sounds good. Make sure you follow the same folder and file structure
as the other HITs.
