### ISSUE TITLE
Typo in HLevels.agda

### ISSUE THREAD

**Issue by phadej** [agda/cubical#151]
https://github.com/agda/cubical/blob/27ec3887d4ea5224f7452d8dcae00818d38a9b2b/Cubical/Foundations/HLevels.agda#L28-L34

Has 

```agda
B : A → Type ℓ
```

should it rather be

```agda
B : A → Type ℓ' -- primed
```

**Comment by Saizan** [comment]
Those two are the same, the ```ℓ``` is actually generalized in the type of ```B```.
