### ISSUE TITLE
Add CI?

### ISSUE THREAD

**Issue by ice1000** [agda/cubical#16]
I think we can make use of CIs to improve PR process and ensure this library is working under at least a specific revision of Agda (and we update this revision from time to time).

Another question: Travis or Circle?

**Comment by mortberg** [comment]
This would indeed be good to have. At the moment the library is supposed to compile on the latest development version of Agda. I think it will stay like this at least until the next major release and then things should be a bit more stable. 

I have used Travis in the past and I liked it. Can you please set it up?

**Comment by ice1000** [comment]
Yes sure. But I'm not an admin to this repo, I need someone (like you or @UlfNorell) to go to Travis website and enable the CI service. I can create a `.travis.yml` to let the CI run the build.

**Comment by mortberg** [comment]
I don't think I have rights to do this either. Maybe @Saizan can do it?

**Comment by ice1000** [comment]
Cool!

**Comment by ice1000** [comment]
Closing as #29 is merged.
