### ISSUE TITLE
The binary conversion inverses question

### ISSUE THREAD

**Issue by mrakgr** [agda/cubical#165]
I asked [this](https://stackoverflow.com/questions/57398791/how-should-the-left-and-the-right-inverse-for-binary-conversion-be-proved/) yesterday on SO, but I haven't gotten any bites. At this point I think that people who know Cubical Agda and the people who answer Agda questions on SO do not have much overlap so I am passing it here to see if anybody is interested.

The Cubical library is fairly advanced and I would like to see more tutorial material before I try studying it seriously.

**Comment by mrakgr** [comment]
I just realized that `Cubical.Data.BinNat` has the proofs that I am looking for in cubical style so I'll close this issue.

**Comment by Alizter** [comment]
@mrakgr For future reference, you are welcome to ask all questions about the library here! It's unlikely that many people on SO will notice your question anyway.
