### ISSUE TITLE
Add website generated with the HTML backend like the stdlib?

### ISSUE THREAD

**Issue by ice1000** [agda/cubical#17]
So we can browse this project easier.

BTW I need an admin (like @UlfNorell) to enable gh-pages rendering for this repo.

**Comment by mortberg** [comment]
Can you send me a link so that I can see what it looks like? Also, where would this be hosted?

**Comment by ice1000** [comment]
The stdlib: https://agda.github.io/agda-stdlib

Also we have literate Agda, which allowd us to have: https://ice1000.org/lagda/CubicalAgdaLiterate.html (it's a modified version of your writing! As a CuTT learner, I really appreciate your work!)

**Comment by ice1000** [comment]
Reminder: the codes in both links are clickable.

**Comment by ice1000** [comment]
As you can see from the stdlib's url, you'll know it's gonna be hosted on GitHub Pages.
It's free and https. This also requires an admin (like @UlfNorell) to configure the repository settings to get the gh-pages service enabled.

**Comment by mortberg** [comment]
This looks good. How often does the html pages get generated?

**Comment by ice1000** [comment]
@mortberg We can let the CI do the work. In `agda-stdlib`, we have a `GH_TOKEN` global variable that stores someone's GitHub token which has the rights to push to a branch of `agda-stdlib`.

**Comment by ice1000** [comment]
So every git-push will trigger the change of the website.

**Comment by ice1000** [comment]
I think we can start working on this.

**Comment by ayberkt** [comment]
@ice1000 

> I think we can start working on this.

I second this and can help set it up if an agreement is reached.

**Comment by ice1000** [comment]
You should @ @mortberg or @Saizan because they have admin access to this repo, I don't

**Comment by mortberg** [comment]
What do I need to do? I'm very busy with other things at the moment, so I won't have time to do any work on this until the end of the semester. But if it's just about giving some rights then I can try to do it quickly

**Comment by ayberkt** [comment]
This is not really an urgent matter and we can address it later. I tried looking at the CI machinery and it seems more complicated than I expected.

Perhaps, someone more familiar with it can tweak it to call `agda --html` and then tell Travis to publish the generated HTML. I think that should be all? If that's the case, this should be quite easy but as @ice1000 pointed out, GitHub Pages will have to be enabled.

**Comment by ice1000** [comment]
As well as Travis CI. You need to configure an access token for it

**Comment by ice1000** [comment]
HoTT-Coq has this: https://github.com/HoTT/HoTT/pull/191

**Comment by mortberg** [comment]
@ice1000 If we're going to do anything about this now might be a good time that we're all working on the library at the same time. Do you think we should do something now?

**Comment by ice1000** [comment]
Surely. When do we do that?

**Comment by mortberg** [comment]
Maybe Tuesday next week? Do we need to involve someone else? 

Note that I'm really clueless about how these things work, but I'm of course happy to help out with providing whatever rights needed to set it up :-)

**Comment by ice1000** [comment]
I guess Tuesday works for me, let's see :) I'll try to reach you on AIM.

**Comment by ayberkt** [comment]
Until this issue is addressed, those who would like to browse `cubical` in HTML can use [the pages](https://www.cs.bham.ac.uk/~axt978/semantics/Cubical.Core.Everything.html) that are automatically generated when I generate HTML from my development that uses `cubical`.

**Comment by ice1000** [comment]
Similarly I have [this page](https://ice1000.org/lagda/Cubical.Core.Everything.html)

**Comment by brendanzab** [comment]
Just wanna say that this would be greatly appreciated! I've been really glad that the generated [
Agda Categories](https://agda.github.io/agda-categories/index.html) files are available - it's much easier to navigate those as opposed to the sources on Github.

**Comment by brendanzab** [comment]
If you are already using github pages then you might be able to use [this action](https://github.com/marketplace/actions/deploy-to-github-pages) to deploy in a pretty pain-free way (I don't think it even requires a token now). I'd recommend making a `.github/workflows/cd-ubuntu.yaml` file that runs on pushes to master, builds the HTML doc, then runs the `JamesIves/github-pages-deploy-action` to upload the output directory to pages.
