### ISSUE TITLE
user-manual and Cubical/Core/README.md are outdated

### ISSUE THREAD

**Issue by andreasabel** [agda/cubical#172]
https://github.com/agda/cubical/blob/master/Cubical/Core/README.md mentions HoTT-UF which does not exist.

This is referred from agda/doc/user-manual/language/cubical, which is likely outdated.

**Comment by m-yac** [comment]
I think this the README part of #72. While we're talking about README's, it would nice if `Cubical/Foundations` had one as well.

**Comment by Saizan** [comment]
Right, HoTT-UF got moved to Cubical.Foundations.HoTT-UF
