### ISSUE TITLE
`stack install` for stack instructions

### ISSUE THREAD

**Issue by anqurvanillapy** [agda/cubical#177]
The stack instructions in `INSTALL.md` say that we should add the build directory to `$PATH`, after following commands:

```bash
$ stack setup
$ stack build
```

But use `stack install` the artifacts (`agda` and `agda-mode`) can be copied to `~/.local/bin`.  This should be a preferred way to install the binaries.

**Comment by ice1000** [comment]
I agree. /cc @mortberg
