### ISSUE TITLE
What is the intuitive explanation for the glue and unglue primitives?

### ISSUE THREAD

**Issue by mrakgr** [agda/cubical#178]
```
-- Using the equality between binary and unary numbers we can get an
-- equality between the two implementations of the NatImpl interface
NatImplℕ≡Binℕ : PathP (λ i → NatImpl (Binℕ≡ℕ (~ i))) NatImplℕ NatImplBinℕ
z (NatImplℕ≡Binℕ i) = transp (λ j → Binℕ≡ℕ (~ i ∨ ~ j)) (~ i) zero
s (NatImplℕ≡Binℕ i) =
  λ x → glue (λ { (i = i0) → suc x
                ; (i = i1) → sucBinℕ x })
             -- We need to do use and hcomp to do and endpoint
             -- correction as "suc (unglue x)" connects "suc x"
             -- with "suc (Binℕ→ℕ x)" along i (which makes sense as
             -- x varies from ℕ to Binℕ along i), but we need
             -- something from "suc x" to "Binℕ→ℕ (sucBinℕ x)" for
             -- the glue to be well-formed
             (hcomp (λ j → λ { (i = i0) → suc x
                             ; (i = i1) → Binℕ→ℕsuc x j })
                    (suc (unglue (i ∨ ~ i) x)))
```

This is from the `BinNat` module. Considering that all this function is an equality between `NatImplℕ` and `NatImplBinℕ` it feels breathtakingly complex.

```
NatImplℕ≡Binℕ : PathP (λ i → NatImpl (Binℕ≡ℕ (~ i))) NatImplℕ NatImplBinℕ
z (NatImplℕ≡Binℕ i) = transp (λ j → Binℕ≡ℕ (~ i ∨ ~ j)) (~ i) zero
```

The base part is not too bad.

```
s (NatImplℕ≡Binℕ i) =
  λ x → glue (λ { (i = i0) → suc x
                ; (i = i1) → sucBinℕ x })
```

This part I can tell is essentially tying together `suc x` and `sucBinℕ x`.

```
             (hcomp (λ j → λ { (i = i0) → suc x
                             ; (i = i1) → Binℕ→ℕsuc x j })
                    (suc (unglue (i ∨ ~ i) x)))
```

This part is what is mind boggling to me. At this point `x : Binℕ≡ℕ (~ i)`. And unglue just turns it into an `ℕ` after which it is incremented.

Right now I am thinking what `(i = i1) → Binℕ→ℕsuc x j` is doing. If I replace it with a hole, I get...

```
Goal: ℕ
————————————————————————————————————————————————————————————
i : I
j : I
x : Binℕ≡ℕ i0
———— Constraints ———————————————————————————————————————————
[1164] (?0 (x = x) (j = i1)) = (Binℕ→ℕ (sucBinℕ x)) : ℕ
[1161] (suc (Binℕ→ℕ x)) = (?0 (x = x) (j = i0)) : ℕ
```

And `Binℕ→ℕsuc` is of type `(x : Binℕ) → suc (Binℕ→ℕ x) ≡ Binℕ→ℕ (sucBinℕ x)`. Meaning the two constraints once they are brought together are asking me to prove ` (suc (Binℕ→ℕ x)) = (Binℕ→ℕ (sucBinℕ x))`. Why is it asking me to prove that? Where are the two constraints coming from?

```
glue   : ∀ {ℓ ℓ'} {A : Set ℓ} {φ : I}
  → {T : Partial φ (Set ℓ')} → {e : PartialP φ (λ o → T o ≃ A)}
  → (t : PartialP φ T) → (a : A) → primGlue A T e

unglue : {A : Type ℓ} (φ : I) {T : Partial φ (Type ℓ')}
         {e : PartialP φ (λ o → T o ≃ A)} → primGlue A T e → A
```

How are the constructor and eliminator intended to be interpreted? When I saw the `ua` code in the docs I got the sense that `Glue` (or `primGlue` in this case) is an equality, but these two seem to operate at a lower level in the type hierarchy than that. As was the case for the previous batch of primitives that I studied, I do not think that the types of them are helpful for understanding their functionality and reasoning about dataflow is required instead.

**Comment by mrakgr** [comment]
```
NatImplℕ≡Binℕ : PathP (λ i → NatImpl (Binℕ≡ℕ (~ i))) NatImplℕ NatImplBinℕ
z (NatImplℕ≡Binℕ i) = transp (λ j → Binℕ≡ℕ (~ i ∨ ~ j)) (~ i) zero
s (NatImplℕ≡Binℕ i) =
  λ x → glue (λ { (i = i0) → suc x
                ; (i = i1) → sucBinℕ x })
             (hcomp (λ j → λ { (i = i0) → suc x
                             ; (i = i1) → Binℕ→ℕsuc x j })
                    (suc (unglue (i ∨ ~ i) x)))
```

I think I get the essential elements of this.

First, what `unglue` does is leaves `x` as the original type `ℕ` when `i = i0`. When it is `i = i1`, it applies `Binℕ→ℕ` to it and converts it from type `Binℕ` to `ℕ`.

Then `suc` turns them into `suc x` and suc `suc (Binℕ→ℕ x)` when `i` is `i0` and `i1` respectively.

`hcomp` maps them to `suc x` and `Binℕ→ℕ (sucBinℕ x)`.

Then `glue` undoes what `unglue` did and maps them to `suc x` and `sucBinℕ x`.

This makes sense and should be the correct trace through the program, but it is hardly a complete explanation. While it explains what is going on on the surface, the underlying mechanisms still need further elucidation.

```
glue   : ∀ {ℓ ℓ'} {A : Set ℓ} {φ : I}
  → {T : Partial φ (Set ℓ')} → {e : PartialP φ (λ o → T o ≃ A)}
  → (t : PartialP φ T) → (a : A) → primGlue A T e

unglue : {A : Type ℓ} (φ : I) {T : Partial φ (Type ℓ')}
         {e : PartialP φ (λ o → T o ≃ A)} → primGlue A T e → A
```

I still do not see how what is being done above matches the type signatures of these. Furthermore, how could it be possible to infer the implicit `{e : PartialP φ (λ o → T o ≃ A)}` argument? I am suspicious about that.

**Comment by mrakgr** [comment]
I figured it out.

```
ua : ∀ {A B : Type ℓ} → A ≃ B → A ≡ B
ua {A = A} {B = B} e i = Glue B (λ { (i = i0) → (A , e)
                                   ; (i = i1) → (B , idEquiv B) })
```

I really found this unusual at first. I thought that `Glue` produced an instance of a path type, but I neglected the `i` argument in the last position. Meaning, `Glue` actually produces an instance of an applied path type. More precisely, the whole expression reduces to `A` when `i = i0` and `B` when `i = i1`.

```
glue   : ∀ {ℓ ℓ'} {A : Set ℓ} {φ : I}
  → {T : Partial φ (Set ℓ')} → {e : PartialP φ (λ o → T o ≃ A)}
  → (t : PartialP φ T) → (a : A) → primGlue A T e

unglue : {A : Type ℓ} (φ : I) {T : Partial φ (Type ℓ')}
         {e : PartialP φ (λ o → T o ≃ A)} → primGlue A T e → A
```

With that in mind, the way to view `glue` and `unglue` is like concurrent joining and forking of processes. Depending on the state of `φ`, one can imagine that `glue` is a function of either `A → A` or `A → T`, and `unglue` is a function of either `A → A` or `T → A`.

```
z (NatImplℕ≡Binℕ i) = transp (λ j → Binℕ≡ℕ (~ i ∨ ~ j)) (~ i) zero
```

As soon as I thought that I imagined that it might be possible to rewrite the first case using `glue` rather than `transp`.

```
z (NatImplℕ≡Binℕ i) = 
  glue (λ { (i = i0) → zero
          ; (i = i1) → binℕ0 }) zero
```

And it worked! It seems Agda's inference when it comes to equivalences is pretty decent.

**Comment by mrakgr** [comment]
I find it really interesting how in the `NatImplℕ≡Binℕ` example it is unnecessary to do an induction, but tracing through it, I find that everything checks out. One step really does seem to be all that is necessary.

**Comment by Rotsor** [comment]
Thanks, that was helpful as I'm trying to follow along the same example.
About inference of equivalences, I think the reason it's so "magically good" is that the type `Glue A e` we're destructing/constructing by `unglue`/`glue` is known and `e` is determined by that.

**Comment by Rotsor** [comment]
By the way, I was confused by the types of `glue` and `unglue` for a long time too.
However, it looks that with the help of `Sub` you can write down types that explain what's going on much better!

```
unglue-S : {A : Type ℓ} (φ : I) {T : Partial φ (Type ℓ')}
         {e : PartialP φ (λ o → T o ≃ A)} → (x : primGlue A T e) → Sub A φ (λ { (φ = i1) → e 1=1 .fst x })
unglue-S φ x = inS (prim^unglue {φ = φ} x)

glue-S   : ∀ {ℓ ℓ'} {A : Set ℓ} {φ : I}
  → {T : Partial φ (Set ℓ')} → {e : PartialP φ (λ o → T o ≃ A)}
  → (t : PartialP φ T) → Sub A φ (λ { (φ = i1) → e 1=1 .fst (t 1=1) }) → Sub (primGlue A T e) φ (λ { (φ = i1) → t 1=1 })
glue-S t a = inS (glue t (outS a))
```
