### ISSUE TITLE
Definition of Square and isSet'

### ISSUE THREAD

**Issue by Saizan** [agda/cubical#182]
The definition of `Square` in the library order the paths by going around the perimeter, and then `isSet'` shuffles them around again.
https://github.com/agda/cubical/blob/c9fc29e4677002122f497de8618b886f0ba61898/Cubical/Foundations/Prelude.agda#L185-L195

I think the best order is to pair up opposite sides, since that matches up nicely with the nested `PathP`s:
```
Square p q r s = PathP (λ i → r i ≡ s i) p q
```

also we should be consistent about it, at least when there's only one square talked about.

**Comment by Alizter** [comment]
The order in Licata-Brunerie is left up right down, but I prefer left right up down.
