### ISSUE TITLE
Use Gitter instead of GitHub issues for discussion?

### ISSUE THREAD

**Issue by ice1000** [agda/cubical#187]
[![Gitter](https://badges.gitter.im/agda/cubical.svg)](https://gitter.im/agda/cubical?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

We may use Gitter to supersede #77. Does this sound like a plan? @mortberg

**Comment by mortberg** [comment]
Sure, good idea! I'll try to remember to stay logged in on Gitter
