### ISSUE TITLE
Naming convention?

### ISSUE THREAD

**Issue by ice1000** [agda/cubical#19]
I see the definitions' names are in a mess, names like `binnat`, `HitInt` are used together .
Should we have a convention for naming? Like following the stdlib directly?

**Comment by mortberg** [comment]
Yes, there is currently no naming convention. It might be a good idea to follow the HoTT-Agda convention (https://github.com/HoTT/HoTT-Agda) as we wouldn't have to think about changing names when porting developments from there.

Can you send me a link to the conventions for the standard library so that I can compare?

**Comment by MatthewDaggitt** [comment]
> Can you send me a link to the conventions for the standard library so that I can compare?

Haha, I wish we were this organised. There is a very bare-bones skeleton of a style guide [here](https://github.com/agda/agda-stdlib/blob/master/notes/style-guide.md) but mostly the convention is unspoken and is enforced by either @gallais or I coming down hard on names we don't like :laughing: I'll try and flesh it out a bit more in the next couple of days.

**Comment by mortberg** [comment]
@MatthewDaggitt Thanks! I like the stylistic choices. I think I'll use the HoTT-Agda naming conventions and the stdlib style guide for things like indentation.

**Comment by riaqn** [comment]
I think having a function named `elimPropTrunc` is kind of superflous when it's already in the file `PropTrunc/Properties.agda`. It's better to just call it `elim`. Then when other files import it, they can change the qualified name.
```
import Data.HITs.PropTrunc as PropTrunc

foo = ... PropTrunc.elim ...
```

This also kinds of gives a structure to the names, which is nice.

**Comment by riaqn** [comment]
Speaking of qualified import, I think we should avoid unqualifed import as much as possible, except for maybe things from `Core`. This practice from Haskell is nice:
```
open import Data.HITs.PropTrunc (||_||)
import Data.HITs.PropTrunc as PropTrunc
```

**Comment by gallais** [comment]
In Agda, the example

```
open import Data.HITs.PropTrunc (||_||)
import Data.HITs.PropTrunc as PropTrunc
```

can be written

```agda
open import Data.HITs.PropTrunc as PropTrunc using (||_||)
```

**Comment by mortberg** [comment]
Closing this now that we finally merged https://github.com/agda/cubical/pull/451
