### ISSUE TITLE
Implicit level parameters for internal structure

### ISSUE THREAD

**Issue by dolio** [agda/cubical#195]
I wanted to get an opinion on a change I've made locally during some stuff I've been working on. Specifically, it seems like there are several definitions in the cubical library that have implicit level parameters that are only determined by the values of that type. The most obvious examples are the truncated universes like:

    hProp : Type (ℓ-suc ℓ)
    hProp {ℓ} = Σ (Type ℓ) isProp

Agda is not very good at inferring `ℓ` for these. I think it mainly happens when you are giving a value of `hProp`, but when you are taking an argument, you end up needing to write the implicit argument explicitly. I think _most_ of the uses of these types in the library end up needing to specify the arguments explicitly.

So, it seems like it doesn't make much sense for these to be implicit in the first place. They're also rather analogous to `Type`, which also doesn't take its argument implicitly, and _shouldn't_ for the same reason.

So, would a patch making this change be accepted?

I think structures like `Group` should probably get the same treatment. `isGroup` works fine, because its level is determined by its argument, but there are almost no cases where `Group`'s implicit argument is actually inferred.

**Comment by Saizan** [comment]
Yeah, we should make those levels explicit.
