### ISSUE TITLE
hlevel indexing

### ISSUE THREAD

**Issue by ecavallo** [agda/cubical#211]
This was discussed a bit in #155. Currently the library indexes hlevels from contractible=0 but truncations (∥_∥,∥_∥₀,∥_∥₁) from contractible=-2, which can be confusing. Given that different parts of the community have different conventions for these things, I'm partial to the approach we tried in [redtt](https://github.com/RedPRL/redtt/blob/master/library/prelude/hlevel.red), which was to use names for hlevels and avoid committing to some mapping onto integers.
```
data hLevel : Type₀ where
  contr : hLevel
  suc : hLevel → hLevel

pattern prop = suc contr
pattern set = suc prop

_-gpd : ℕ → hLevel
zero -gpd = set
suc n -gpd = suc (n -gpd)

...
```
The disadvantages of introducing a new type (as opposed to using ℕ as we are now) are that (a) we'll have to introduce conversions between `ℕ` and `hLevel` in various places, (b) we may have to re-prove various arithmetical facts about adding hlevels together and so on. But I think both of these lead to more readable code in the long term, and (b) is mostly an upfront cost.

Thoughts?

**Comment by Saizan** [comment]
I suppose we could also have the following somewhere:

```
open import Agda.Builtin.Nat public renaming (Nat to hLevel; zero to contr)
```

which sidesteps both (a) and (b), though I guess it's unfortunate that normalizing `contr` will print `0`.

Although with the advantage that I'd rather see `3` than `suc (suc (suc contr))`.

**Comment by ecavallo** [comment]
My concern would be that (once we have general truncation) one could still write `∥ A ∥ 3` and get a surprising result.

**Comment by Saizan** [comment]
I guess because of `pattern` it would show me `suc set`, and in most cases higher than that we are probably dealing with things like `suc n` rather than a concrete index.

I wonder how much of an impact (a) really has?

**Comment by ecavallo** [comment]
I think it doesn't make that much of difference... if you're using `nat` for hlevels, then you end up putting `2 +` (or something like that) in the same places anyway.

**Comment by m-yac** [comment]
I think the code in https://github.com/m-yac/cubical/commit/309f3ed021be2ccf993f461ad9254a64039cb950 (referenced in #219) is relevant to this issue. Literals for `ℕ₋₁` are defined so that `∥ A ∥ -1` is propositional truncation, `∥ A ∥ 0` is set truncation, etc. and the notation is consistent with that in the HoTT book (e.g. one can prove `isOfHLevel 5 (∥ A ∥ 3)`).

**Comment by Saizan** [comment]
@m-yac does the book have a notion of "HLevel" that starts from `0`?

Anyhow, I think it would be better to have a single indexing scheme for both truncations and HLevels.

**Comment by m-yac** [comment]
@Saizan ah it doesn't seem like it does, for some reason I had a memory that it was mentioned somewhere as an alternative.

Well we could very easily refactor `isOfHLevel : ℕ → Type ℓ → Type ℓ` to something of type `ℕ₋₂ → Type ℓ → Type ℓ`. I propose `isOfLevel n A` (as in "A is of truncation level n") for this, but `isTrunc n A` (as in "A is n-truncated") or `is- n -Type A` (or something else) could also work.

**Comment by m-yac** [comment]
As I mentioned in https://github.com/agda/cubical/pull/238#issuecomment-591125633, I'm still not sold about re-indexing to `ℕ₋₂`. If we were to switch, I think `isTrunc : ℕ₋₂ → Type ℓ → Type ℓ` would be best, to complement `isConn : ℕ₋₂ → Type ℓ → Type ℓ` for n-connected types (`isConn n A := isContr (∥ A ∥ n)`). My main concerns are about the readability of proofs about n-truncated types.
