### ISSUE TITLE
Compile error on try compile.

### ISSUE THREAD

**Issue by caotic123** [agda/cubical#225]
When I try to compile with the make, I get this error : 
Agda version :  2.6.0.1

```
A (i ∧ i0) → A (i ∧ i1) !=< A i of type
Set (ℓ-max (ℓ′ (i ∧ i0)) (ℓ′ (i ∧ i1)))
when checking that the inferred type of an application
  A (i ∧ i0) → A (i ∧ i1)
matches the expected type
  A i

```

**Comment by Saizan** [comment]
For `Agda-2.6.0.1` you should try the 0.1 version of this library:
`https://github.com/agda/cubical/releases/tag/v0.1`
