### ISSUE TITLE
Repo description?

### ISSUE THREAD

**Issue by ice1000** [agda/cubical#232]
Can we have a description for the repo?
![image](https://user-images.githubusercontent.com/16398479/73577203-48ed4780-444a-11ea-9dc2-b8f61f5f4e22.png)

Just like agda-stdlib?
![image](https://user-images.githubusercontent.com/16398479/73577249-5f939e80-444a-11ea-92e9-0365b87dcebb.png)

**Comment by ice1000** [comment]
@mortberg @Saizan can you resolve this

**Comment by Saizan** [comment]
done.
