### ISSUE TITLE
naming conventions in HIT/Data properties

### ISSUE THREAD

**Issue by ecavallo** [agda/cubical#241]
Some Data/HITs Properties files contain definitions like `elim`, `ind`, `comm`, etc. that are meant to  used in a qualified import or with `renaming`, while others have names like `elimSetProp`, etc. that incorporate the module name. Thoughts on which the library should prefer? I'm asking because I want to make the names in the various `Truncation` modules consistent with each other.

**Comment by m-yac** [comment]
I've also been thinking about this! I vote for `X-elim`, etc. in module `X`, so there's no ambiguity or extra work to do when importing. I think `elimX` is also reasonable, as the above might look strange in the case of types that are entirely unicode (e.g. `∥∥-elim` vs. `elim∥∥` vs. `elimTrunc`).

This is a slightly different topic, but I also think we should standardize to calling dependent and non-dependent eliminators "elim" and "rec" respectively (and therefore refactor instances of "ind", "induction", and other names for eliminators).

**Comment by m-yac** [comment]
Noting that this has also been discussed in #19, though the conclusion reached there is opposite mine.

**Comment by Saizan** [comment]
The conclusion in #19 suggests to go for plain names like `elim` and then import like this:

```agda
open import Cubical.HITs.Foo as Foo using (FooType; FooCon1; FooCon2; ...)
```

In fact you can even drop the `using` clause as long as you make sure to qualify any ambiguous names: Agda won't complain if you just open multiple modules exporting the same name.

This seems the most usable design to me.

**Comment by mortberg** [comment]
I agree with calling them elim and rec. I have no strong opinions about having unique names in the files or relying on qualified names.

**Comment by ecavallo** [comment]
What should we do in `Everything`? Agda does complain if you re-export multiple modules exporting the same name.

**Comment by Saizan** [comment]
I guess we could add `hiding ...` clauses everywhere.

However I would expect `Cubical.Data.Everything` and `Cubical.HITs.Everything` are not actually used much, (less than e.g. `Cubical.Core.Everything`) and are mostly useful to collect all the modules to test. In that case we could just not open the modules at all.

**Comment by ecavallo** [comment]
Yeah, I think not opening them is the better choice.
