### ISSUE TITLE
Why is pathToEquiv/lineToEquiv in Agda.Builtin.Glue?

### ISSUE THREAD

**Issue by m-yac** [agda/cubical#259]
Seems like it better belongs in `Cubical.Foundations.Transport`, keeping it in a Builtin file makes it seem more mysterious than it is.

...Though maybe it's more mysterious than I think: Is the construction of `pathToEquiv` in `Agda.Builtin.Glue` any better than `isoToEquiv (pathToIso p)` in `Cubical.Foundations.Transport`? My understanding is that the key property `pathToEquiv` has is that `invEq (pathToEquiv)` is definitionally equal to `transport⁻ p`, but both have this property. Is the fiber contraction of `pathToEquiv` superior to `isoToEquiv (pathToIso p)` in some way?

**Comment by mortberg** [comment]
@Saizan Is pathToEquiv/lineToEquiv used internally these days? I guess you might not use it anymore after implementing the direct definition for transport in hcomp U? If so then it could be moved out of Agda.Builtin.Glue.

I don't remember if `pathToEquiv` is better than the other definition... It looks kind of scary, but it might still be a bit smaller than `isoToEquiv (pathToIso p)`

**Comment by Saizan** [comment]
No, it's not used internally anymore, we could move it.

I would guess that the inverse you get out of the equiv is simpler than what you get from `isoToEquiv` but I have not checked.

**Comment by mortberg** [comment]
@Saizan What should we do about this issue?

**Comment by Saizan** [comment]
Put the `pathToEquiv` code into this library somewhere?

**Comment by mortberg** [comment]
Actually we rename it to `lineToEquiv`

https://github.com/agda/cubical/blob/master/Cubical/Core/Glue.agda#L40 

and this is then only used in one place in the whole library

https://github.com/agda/cubical/blob/master/Cubical/Foundations/Univalence.agda#L195

So we should probably just inline it there?


Note that there's of course a much simpler proof of this: https://github.com/agda/cubical/blob/master/Cubical/Foundations/Univalence.agda#L215

Do you think it would be worse to use that proof instead?

**Comment by Saizan** [comment]
It would probably be worse to use `eqweqmap`, while `pathToIso` might be very close.

It would be fine to inline `lineToEquiv` into `pathToEquiv`.

**Comment by mortberg** [comment]
Yeah, let's inline `lineToEquiv` in `pathToEquiv` then!

Does anyone have time to fix this? I guess it will involve making a PR to Agda (deleting the `lineToEquiv` code) and a PR to agda/cubical (adding the `lineToEquiv` code in a `where` for `pathToEquiv`). I guess these should be merged at the same time and everyone will have to update their Agda installations afterwards. 

While we're at it, is there anything else that should be moved from the Agda cubical builtins to the library?

**Comment by Saizan** [comment]
You can do the changes to agda/cubical before any changes to Agda, I would think.

**Comment by mortberg** [comment]
Oh, right! I was confused. The PR to agda/cubical will just inline the proof and remove the renaming from 

https://github.com/agda/cubical/blob/master/Cubical/Core/Glue.agda#L40

We can then remove the code from Agda in another PR.
