### ISSUE TITLE
Nomenclature of Categories

### ISSUE THREAD

**Issue by Schippmunk** [agda/cubical#263]
To be consistent with Book HoTT Terminology, the names of the currently present kinds of categories should be changed as follows:

What is currently a precategory is actually a [wild category](https://ncatlab.org/homotopytypetheory/show/wild+category).
The current definition of category is just a precategory in the HoTT book: a wild category where the hom types are sets.

If you agree with these changes I will create an appropriate PR.

**Comment by jonsterling** [comment]
For what it's worth, I followed the UniMath terminology rather than the Book HoTT terminology. I don't feel too strongly about it though.

**Comment by Schippmunk** [comment]
Oh, that's fair. I wasn't aware a different standard existed.

**Comment by m-yac** [comment]
[Unimath has a good table](https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/README.md) summarizing this difference, to which I added an extra column with the nomenclature from [this paper by Paolo Capriotti and Nicolai Kraus](https://arxiv.org/abs/1707.03693):

| UniMath                      | Capriotti-Kraus    | HoTT Book       | Ob   | Hom   | Univalence |
|------------------------------|--------------------|-----------------|------|-------|------------|
| Precategory                  | Wild Precategory   | n/a             | Type | Type  | No         |
| Category                     | Precategory        | Precategory     | Type | Set   | No         |
| Univalent/saturated category | Univalent category | Category        | Type | Set   | Yes        |
| Set category                 | n/a                | Strict category | Set  | Set   | No         |

I'm personally a fan of the nomenclature in Capriotti-Kraus, as it calls nothing a "category"! This was the conclusion I drew from a long thread on the HoTT mailing list recently - all the above notions of 'category' are sufficiently different from the notion of 'category' in set theory that, to avoid conclusion, all of them should be qualified with something. That being said, I also don't feel too strongly about it.

**Comment by mortberg** [comment]
I like the UniMath terminology and think we should stick to it

**Comment by mortberg** [comment]
It might be a good idea to add a comment about this to avoid confusing people who read the HoTT book

**Comment by Schippmunk** [comment]
Thanks for the table m-yac. I agree with you.
Adding more comments also sounds like a reasonable compromise. I will take care of that and close this issue.
