### ISSUE TITLE
Should we ever index from -2?

### ISSUE THREAD

**Issue by m-yac** [agda/cubical#266]
Now that #253 is merged, n-truncation is indexed by `ℕ` instead of `ℕ₋₂`, but  `∥ A ∥_ : ℕ₋₂ → Type ℓ` is still exposed, following @mortberg's suggestion [in this comment](https://github.com/agda/cubical/pull/238#issuecomment-592397566) to "work internally with ℕ but also expose standard interfaces with ℕ₋₂". Having this interface could be nice for stating/proving some theorems.

However, we have no `ℕ₋₂`-indexed analog of `isOfHLevel`, and therefore no `ℕ₋₂`-indexed analogs of basic h-level lemmas, so when actually doing almost anything with `∥ A ∥ n`, one is forced to use `ℕ` anyway – essentially the negating the purpose of including this type.

The only solution I can see is making a file which is a duplicate of `Foundations.HLevels` containing `ℕ₋₂`-indexed versions of every definition (e.g. `isOfHLevel` → `isTrunc`, `isOfHLevelPath` → `isTruncPath`, etc. etc.), but this seems a little ridiculous.

Thoughts? Other ideas?

**Comment by ecavallo** [comment]
I'm in favor of picking one indexing and sticking with it.

**Comment by mortberg** [comment]
> I'm in favor of picking one indexing convention and sticking with it.

Me too. I think it's a bit silly to index from `-2` and having to redo lots of theory about `ℕ₋₂` when we can just use `ℕ` everywhere. The only problem is that some results will be shifted by 2 compared to the HoTT version, so it is important to have names that are not identical to the HoTT ones so that they're suggestive of the difference (like including "h" or "hLevel" in the names of things).

**Comment by Saizan** [comment]
Regarding naming, i think the distinguishing keyword is really "Level", the homotopy part less so.
We can shorten that to "Lvl" if we want.

We can also have `HLevel = ℕ` defined in `.HLevels` and use it in types as documentation.

I would also expect that `∥ A ∥_ : HLevel → Type ℓ` would be fine to have if documented properly, so we can use the pretty syntax for a useful type.

**Comment by UlrikBuchholtz** [comment]
On the spectral sequence project we needed quite a bit of (affine) arithmetic with levels. This happens with truncated and connected spectra, for instance, but of course also with smash connectivity and Blakers–Massey and stuff like that. I always thought it might be nice to take levels to be the subtype of the integers that are at least -2, for this reason.

**Comment by UlrikBuchholtz** [comment]
Another option is to define the levels to *be* the integers, and say z-truncated means contractible for z ≤ -2, etc.

**Comment by guillaumebrunerie** [comment]
@UlrikBuchholtz But then it’s probably somewhat more awkward to define something by recursion on a level (at least in Agda).

**Comment by Saizan** [comment]
@UlrikBuchholtz are you saying truncated subtraction wouldn't work well for those applications?

**Comment by UlrikBuchholtz** [comment]
> @UlrikBuchholtz But then it’s probably somewhat more awkward to define something by recursion on a level (at least in Agda).

If ≤ on the integers is defined inductively in terms of refl : x ≤ x and step : x ≤ y → x ≤ y + 1, then it should work mostly the same, right?

(BTW, wasn't there also some work on implementing custom “views” for types such that user-defined recursors could be used for pattern matching?)

> @UlrikBuchholtz are you saying truncated subtraction wouldn't work well for those applications?

It's mostly addition together with truncated subtraction (e.g., for Blakers–Massey you need addition of truncation levels (so n + m - 2 on hlevels)). Of course it's possible, but it gets annoying fiddling with the conversions. For instance, see [spectrum/trunc.hlean](https://github.com/cmu-phil/Spectral/blob/master/spectrum/trunc.hlean) where we have a lot of little things about ```maxm2``` (max of an integer and -2 to get a truncation level). Then we needed properties of this ([here](https://github.com/leanprover/lean2/blob/master/hott/types/trunc.hlean#L1143)), which would all follow directly from general facts about integers.

Maybe if we ping @fpvandoorn we'll hear more about the pain points.

**Comment by guillaumebrunerie** [comment]
> > @UlrikBuchholtz But then it’s probably somewhat more awkward to define something by recursion on a level (at least in Agda).
> 
> If ≤ on the integers is defined inductively in terms of refl : x ≤ x and step : x ≤ y → x ≤ y + 1, then it should work mostly the same, right?

Agda’s pattern matching works very well for structural induction, but not so much for other kinds of induction. What I have in mind is simple structural inductions like
```agda
f : Nat → A
f O     = […]
f (S n) = [… f n …]
```
This cannot be written as easily if `Nat` is defined as a subtype of `Int`.

> (BTW, wasn't there also some work on implementing custom “views” for types such that user-defined recursors could be used for pattern matching?)

I haven’t heard about that, but that would probably be nice to have!

**Comment by fpvandoorn** [comment]
I agree with @ecavallo that it's good to stick with one definition. 

I think all options have their own advantages and disadvantages.
* `ℕ`: requires least setup, but some statements might look a little weird. I think this is a good option. When adding levels, you can indeed use `n + m - 2`. There will be some superfluous `+2`'s when a natural number is both used for homotopy groups and as a truncation level, but maybe that is better than an (mostly invisible) coercion.
* `ℕ₋₂`: statements look nicest, but requires a lot of setup. We did this in Lean, but I have sometimes wondered whether the slightly nicer statement was worth all of the hassle with coercions and extra libraries needed for `ℕ₋₂`.
* `Int`: This is nice when defining `Int`-indexed truncation/truncatedness for spectra. It is less convenient when working with types, so I don't think this is a very good option. Moving to `Int` later requires some work, but it's a one-time cost thing, so not too bad.

**Comment by UlrikBuchholtz** [comment]
Thanks, @fpvandoorn ! It sounds like the best option for types then is to use ```ℕ```, even though it requires duplicate definitions for many concepts for Nat and Int.

I wonder also whether we'll end up using hlevels for spectra, so that abelians groups are spectra of hlevel 2 that are hlevel-1-connected. Looks a bit weird at first, but ultimately not worse than sets being at hlevel 2.

**Comment by fpvandoorn** [comment]
> I wonder also whether we'll end up using hlevels for spectra, so that abelians groups are spectra of hlevel 2 that are hlevel-1-connected. Looks a bit weird at first, but ultimately not worse than sets being at hlevel 2.

Yeah, I think you should, for the sake of consistency.

**Comment by mortberg** [comment]
> I agree with @ecavallo that it's good to stick with one definition.
> 
> I think all options have their own advantages and disadvantages.
> 
>     * `ℕ`: requires least setup, but some statements might look a little weird. I think this is a good option. When adding levels, you can indeed use `n + m - 2`. There will be some superfluous `+2`'s when a natural number is both used for homotopy groups and as a truncation level, but maybe that is better than an (mostly invisible) coercion.
> 
>     * `ℕ₋₂`: statements look nicest, but requires a lot of setup. We did this in Lean, but I have sometimes wondered whether the slightly nicer statement was worth all of the hassle with coercions and extra libraries needed for `ℕ₋₂`.
> 
>     * `Int`: This is nice when defining `Int`-indexed truncation/truncatedness for spectra. It is less convenient when working with types, so I don't think this is a very good option. Moving to `Int` later requires some work, but it's a one-time cost thing, so not too bad.

Thanks for this summary! I'm now convinced that using `ℕ` is preferable to `ℕ₋₂` for the library. When formalizing mathematics I don't want to struggle with all the hassle related to making `ℕ₋₂` work smoothly but instead focus on the mathematics.

I also like @Saizan 's idea to define `HLevel = ℕ` and use things like `∥ A ∥_ : HLevel → Type ℓ` throughout the library. That's nicer than polluting the names.

**Comment by m-yac** [comment]
I've made a pull request with these changes: #302

Thank you to everyone for this really enlightening discussion! I'm confident `ℕ` is the right choice now.

**Comment by mortberg** [comment]
This has been fixed now and we're using `ℕ` everywhere thanks to @m-yac
