### ISSUE TITLE
Rename `_×_` to `Pair` and `_×Σ_` to `_×_`

### ISSUE THREAD

**Issue by Saizan** [agda/cubical#272]
I'm much more likely to use the product that's a special case of `Σ` rather than one defined as an inductive type.

What I'm proposing to call `Pair` was defined to get more expanded normal forms for some examples in the paper. That's not often what you want though.

**Comment by mortberg** [comment]
I agree. I think we almost always use ×Σ so let's make it the standard definition of × and put it in Data.Sigma
