### ISSUE TITLE
Prove more stuff about pointed types

### ISSUE THREAD

**Issue by mortberg** [agda/cubical#278]
It would be nice to port https://github.com/mortberg/cubicaltt/blob/master/examples/pointedMaps.ctt to Cubical Agda. This might benefit from https://github.com/agda/cubical/blob/master/Cubical/Structures/Pointed.agda

**Comment by UlrikBuchholtz** [comment]
Right now [Π∙](https://github.com/agda/cubical/blob/master/Cubical/Foundations/Pointed/Properties.agda#L11) is defined in terms of a family of pointed types, but that's not the most useful pointed Pi: There we just need the fiber over the base point to be pointed. That way, pointed homotopies become elements of pointed Pi's. Shall I try to rework that? (Of course, for the pointed Pi type itself to be pointed, you need a family of pointed types, but from the latter you can extract the base point in the fiber over the base point.)

**Comment by mortberg** [comment]
Yes, that sounds like a good thing to implement!
