### ISSUE TITLE
Generate clickable HTML and publish using GitHub pages

### ISSUE THREAD

**Issue by ayberkt** [agda/cubical#294]
It would be extremely convenient to have a continuously published clickable HTML rendering of this library.

Since there is an existing CI setup, this should be really easy to do. However, using GitHub actions might be a nicer solution for this so perhaps #222 is a dependency.

**Comment by ayberkt** [comment]
I just noticed that there is an existing issue (#17) on this.

**Comment by ice1000** [comment]
Duplicate of #17
