### ISSUE TITLE
Add a contributing guideline

### ISSUE THREAD

**Issue by ayberkt** [agda/cubical#317]
It might be useful to have a file containing basic information (e.g. [`CONTRIBUTING.md`](https://github.blog/2012-09-17-contributing-guidelines/)) on how to contribute to `cubical`.

**Comment by mortberg** [comment]
Yes! I've been meaning to do this for a while and have a local draft somewhere. I can make a PR with it soon so that we can discuss

**Comment by ayberkt** [comment]
Nice! Here is a question I have that would maybe answered in this guideline: when one adds a new file in a PR, should one include it in some file for it to be included in the CI checks? If yes, how would one find the right file?

**Comment by ayberkt** [comment]
Another question: is there a line limit that contributors should adhere to (e.g. 80 characters)?

**Comment by mortberg** [comment]
> Nice! Here is a question I have that would maybe answered in this guideline: when one adds a new file in a PR, should one include it in some file for it to be included in the CI checks? If yes, how would one find the right file?

As of https://github.com/agda/cubical/pull/268 you don't have to add anything manually unless your file are in Core, Foundations, Codata or Experiments. I'll add it to the contributing file
