### ISSUE TITLE
Get rid of recElim for truncation

### ISSUE THREAD

**Issue by mortberg** [agda/cubical#319]
The cohomology code relies on the recursor for truncation being defined in terms of the eliminator. The problem is that this makes the recursor a lot more complicated than necessary, however changing to the simpler definition breaks the cohomology code. 

@aljungstrom : Can you please fix this? It is always a bad sign if some proofs rely on the exact definition of some term like this. This typically indicate some leaky abstraction which very often lead to inefficient proofs, so by fixing this issue the cohomology code should hopefully become a lot faster to typecheck.

**Comment by WorldSEnder** [comment]
https://github.com/WorldSEnder/cubical/commit/190e467003c9d0f0a6901f5417448ea52f2b69e4 has a working definition with the recursor as defined in 298fc9abce524f53aaf3305338e2af73794f57a9. Also has a workaround for #320 that, on my end, speeds up typechecking.

**Comment by mortberg** [comment]
Wow, that was quick! Can you make a PR?

**Comment by WorldSEnder** [comment]
See #322
