### ISSUE TITLE
Typechecking Cubical.Codata.M.AsLimit.M.Properties  is extremely slow

### ISSUE THREAD

**Issue by mortberg** [agda/cubical#320]
It seems like typechecking this file has become extremely slow. Any clue why @cmester0 ? Is this file really needed?

**Comment by cmester0** [comment]
The file `Cubical.Codata.M.AsLimit.M.Properties` has properties used a lot, when working with M-types, so I think the problem is the definitions of the M-types more than this file. Any file using the M-types will have the same problem.

**Comment by mortberg** [comment]
It probably has to do with `shiftIso`. It would be good to try to simplify it

**Comment by cmester0** [comment]
Yes, I think it is because the definition is large and recursive. I will try and have a look at it at some point, but I am a bit pressed for time currently.

**Comment by mortberg** [comment]
I think this was fixed by https://github.com/agda/cubical/pull/322. In the long run the proper solution would be to optimize and simplify `shiftIso` though
