### ISSUE TITLE
Rename Set to Type

### ISSUE THREAD

**Issue by mortberg** [agda/cubical#327]
Now that https://github.com/agda/agda/pull/4629 has been merged I think we can get rid of https://github.com/agda/cubical/blob/master/Cubical/Core/Primitives.agda#L40 and just rename `Set` to `Type` when importing `Agda.Primitive`

**Comment by mortberg** [comment]
@jespercockx : Thanks a lot for implementing this nice change to Agda! Can you just tell me quickly what I need to do to rename Set to Type globally for this library? I'm sure I can find it by reading through that PR, but if you have time I would really appreciate a short explanation

**Comment by guillaumebrunerie** [comment]
The line where you import `Agda.Primitive` should look have an additional renaming of `Set` to `Type`, just like there is one from `Setω` to `Typeω`.

I believe this is enough (and removing the definitions of `Type` and so on, of course).

**Comment by mortberg** [comment]
Wow, that seems simple enough! I guess the only issue is that the library will break for any version prior to when this PR was merged? But @Saizan made a new release recently so I think this is fine.

**Comment by jespercockx** [comment]
You might also want to add the `--no-import-sorts` flag if you actually want to use `Set` for something else (or you might want to wait until https://github.com/agda/agda/issues/3118 is implemented).

**Comment by mortberg** [comment]
> You might also want to add the `--no-import-sorts` flag if you actually want to use `Set` for something else (or you might want to wait until [agda/agda#3118](https://github.com/agda/agda/issues/3118) is implemented).

Yeah, I realized this and added `--no-import-sorts` to all files in the library in my PR (with the help of sed)
