### ISSUE TITLE
sigmaPath->pathSigma->sigmaPath and pathSigma->sigmaPath->pathSigma are flipped

### ISSUE THREAD

**Issue by endobson** [agda/cubical#332]
I've been reading through a lot of the core code and transcribing over my own copy as a way to better familiarize myself with Agda/Cubical type theory. While doing so and looking at the code for sigmaPath I believe I have found a naming error.

https://github.com/agda/cubical/blob/c64922ab532dfcf8d7d69398ad11a5ca31e4b2ba/Cubical/Data/Sigma/Properties.agda#L128-L129

https://github.com/agda/cubical/blob/c64922ab532dfcf8d7d69398ad11a5ca31e4b2ba/Cubical/Data/Sigma/Properties.agda#L135-L136

In the parts above we have:

```
pathSigma→sigmaPath : (a b : Σ A B) → a ≡ b → a Σ≡T b
...
sigmaPath→pathSigma : (a b : Σ A B) → a Σ≡T b → (a ≡ b)
```

I've been reading this as pathSigma corresponds to the type with `≡` as the top level type constructor, and sigmaPath as the newly introduced type.

Thus my intuition is that `pathSigma->sigmaPath->pathSigma` should be about taking an `a ≡ b` and pushing it through the two conversions and showing the desired equality. Yet it is taking an `a Σ≡T b` and doing the same.

This intuition seems backed up by the naming scheme in other files:
https://github.com/agda/cubical/blob/c64922ab532dfcf8d7d69398ad11a5ca31e4b2ba/Cubical/Data/BinNat/BinNat.agda#L165-L171

**Comment by mortberg** [comment]
Yeah, those names seem wrong. A PR would be very welcome!

I'm also not a huge fan of `Σ≡T` as I can never remember what it means. Maybe it would be better to just have it unfolded everywhere?

**Comment by mortberg** [comment]
Fixed by https://github.com/agda/cubical/pull/337
