### ISSUE TITLE
definition of the n-spheres

### ISSUE THREAD

**Issue by pnlph** [agda/cubical#347]
Hi,

I do not find the definition `_-sphere` from [Cubical Synthetic](https://dl.acm.org/doi/abs/10.1145/3372885.3373825).

Is the name changed or it is still to be added?

Thanks!

**Comment by mortberg** [comment]
I think it has been renamed to https://github.com/agda/cubical/blob/master/Cubical/HITs/Sn/Base.agda 

Is this what you're looking for?

**Comment by pnlph** [comment]
Yes, I think so, thanks! Then, the notation was changed from `n -sphere` to `S n`.

That also answers another question I had about finding `S⁰`. In the paper `S⁰` seems to be represented directly by `Bool` but now it is also a suspension itself, of the empty type.

I see also now the proof of `Bool≃Susp⊥`. I guess what is called `s2c : 1 -sphere → S¹` is now `SuspBool→S¹ : SuspBool → S¹`.

**Comment by mortberg** [comment]
Yeah, some things have changed in the library since we wrote the paper and we also had to compress some names to fit with the small columns. The changes are mostly just renaming and some minor changes in definitions that turned out to be better for more advanced proofs later on.

**Comment by mortberg** [comment]
Btw, if you want to make a useful contribution you can make a new file in a new folder called "Papers" and import everything from that paper but give it the names that we used for the paper. I guess we should have done this when writing the paper, but as usual there was not much time left when the deadline approached. A similar file for the Cubical Agda paper would of course al be appreciated.
