### ISSUE TITLE
How to organize algebraic structures?

### ISSUE THREAD

**Issue by mortberg** [agda/cubical#349]
We have two ways of defining algebraic structures:
- Nested Sigma types
- Records

The benefit of nested Sigma types is that it's easy to apply the SIP. The bad thing is that goals quickly get unreadable, it's very annoying to instantiate structures because they're so deeply nested and it's inefficient. So I think we should use Records for all developments *except* for using the SIP to characterize the equality of the structure. 

For example for groups we would have a definition of Group as a Record and then a module that defines groups as a nested Sigma type, apply the SIP, prove that the Sigma version is equivalent to the Record version and then *only* export the result about the equality for Group structures defined as a Record. All consecutive theory about groups will then be developed for the Record definition. 

I personally think this will be the cleanest way to develop algebra in Cubical Agda despite some boilerplate code for relating nested Sigma types and Records (which could probably be automated). What do others think about this?

Sorry @Edlyr, if we decide for this then your PR https://github.com/agda/cubical/pull/344 will have to be rewritten. I didn't know how annoying it was to actually use the nested Sigma type definitions in Agda (in Coq it's not as bad because of tactics) until I tried to do some basic linear algebra today.

**Comment by mortberg** [comment]
Btw, the issue https://github.com/agda/cubical/issues/288 is related to this one. But let's not worry about automation yet and just try to do everything manually and see how it is to work with the definitions.

**Comment by UlrikBuchholtz** [comment]
Thanks for bringing this up! I'm just now experimenting on an alternative approach using [displayed](https://arxiv.org/abs/1705.04296) ([bi](https://arxiv.org/abs/1903.01152))categories. (Bicategories is the highest level I need for my current project.)

There, rather than having everything defined in terms of a family over the structure carrier, the approach is usually to index over the structure one-level down. (E.g., modules over rings over (abelian) groups over monoids over semigroups over sets (over type).)

Of course that leads to deep left nesting rather than deep right nesting.

But with records, the nesting can be avoid in the indexed/displayed style by including the previous record definition in the new record definitions. The displayed approach also comes with combinators that make it feasible to prove SIP-results (univalence of the corresponding (bi)categories).

**Comment by mortberg** [comment]
> Thanks for bringing this up! I'm just now experimenting on an alternative approach using [displayed](https://arxiv.org/abs/1705.04296) ([bi](https://arxiv.org/abs/1903.01152))categories. (Bicategories is the highest level I need for my current project.)
> 
> There, rather than having everything defined in terms of a family over the structure carrier, the approach is usually to index over the structure one-level down. (E.g., modules over rings over (abelian) groups over monoids over semigroups over sets (over type).)
> 
> Of course that leads to deep left nesting rather than deep right nesting.
> 
> But with records, the nesting can be avoid in the indexed/displayed style by including the previous record definition in the new record definitions. The displayed approach also comes with combinators that make it feasible to prove SIP-results (univalence of the corresponding (bi)categories).

I think I see... One thing I wondered about the displayed approach is whether you always first have to prove that your structures form (bi)categories before proving some kind of SIP result for them?

**Comment by Edlyr** [comment]
Personally I don't see that much of a problem in working with nested sigma types. I think it is better to keep a low-level definition to be able to easily use results like the SIP. Then one can define a module as a higher-level interface to be able to use the structure in a similar manner to a record type.
See for example GroupLemmas in https://github.com/Edlyr/cubical/blob/master/Cubical/Structures/Group/Properties.agda#L8

**Comment by felixwellen** [comment]
@mortberg is that in line with what you have in mind:
https://github.com/felixwellen/cubical/blob/876e81bcf0aac86f8fae132705f853752916b473/Cubical/Structures/Ring.agda#L161-L189
I just wrote this ad hoc, since I did not want to write a nested tuple when constructing examples of rings.

**Comment by mortberg** [comment]
> Personally I don't see that much of a problem in working with nested sigma types. I think it is better to keep a low-level definition to be able to easily use results like the SIP. Then one can define a module as a higher-level interface to be able to use the structure in a similar manner to a record type.
> See for example GroupLemmas in https://github.com/Edlyr/cubical/blob/master/Cubical/Structures/Group/Properties.agda#L8

One reason that I don't like nested Sigma types is that they reduce readability of goals a lot. For instance when working on matrices I was asked to prove the following type of goals:

```
Goal: (x y z : FinMatrix ⟨ R ⟩ n n) →
      snd (snd raw-ring-structure-FinMatrix) x
      (fst raw-ring-structure-FinMatrix y z)
      ≡
      fst raw-ring-structure-FinMatrix
      (snd (snd raw-ring-structure-FinMatrix) x y)
      (snd (snd raw-ring-structure-FinMatrix) x z)
```

In Coq this is not much of a problem because I can just run `simpl` which applies some heuristics to simplify the goal for me. But the only option I know of in Agda is to fully normalize the goal which just makes it worse. With records things would look slightly better at least. There are also efficiency reasons to prefer records to nested Sigma types.

**Comment by mortberg** [comment]
> @mortberg is that in line with what you have in mind:
> https://github.com/felixwellen/cubical/blob/876e81bcf0aac86f8fae132705f853752916b473/Cubical/Structures/Ring.agda#L161-L189
> I just wrote this ad hoc, since I did not want to write a nested tuple when constructing examples of rings.

Yes! But maybe the record should reflect the hierarchy of algebraic structures (a ring is an abelian group with...). It might be a good idea to have the record representation be as close as possible to the Sigma type definition in terms of how the structures are nested in order to make the proofs that they are equivalent as trivial as possible. This might mean that the Sigma type definitions have to be slightly reorganized to better match what is natural as a Record. I think all of this will be clearer when we start implementing this change. 

I can start by rewriting the Monoid file the way I have in mind today and then we can discuss what to do about Group, Ring, CommRing, Poset, etc...

**Comment by mortberg** [comment]
I had a look at how the Agda standard library organizes their algebraic structures: https://agda.github.io/agda-stdlib/Algebra.html

It seems quite reasonable to me and I'm thinking that we could do more or less the same for this library. Maybe someone who's familiar with the standard library can weigh in a tell us if there are some design choices that you would have changed if you would have completely rewritten the Algebra part of the library? Maybe @nad or @MatthewDaggitt have something to share?

**Comment by martinescardo** [comment]
What would be nice is that Agda supported record syntax for defining iterated Sigma types, so that, in particular, we automatically had names for the projections.

**Comment by DavidJaz** [comment]
One difference I would make from the standard library (which I did not work on, I should say), is to make generic definitions for the various properties (associativity, commutativity, distributivity etc.) so that one could for example say 
`assoc : _+_ is-associative`
for example. But also, to make sure these definitions are generic as possible to accomodate modules and multi-sorted algebraic theories generally. For example, instead of doing associativity for a single operation, we could do it for two operations

`is-associative : {A B C : Type} (_+_ : A -> B -> B) (_++_ : B ->  C -> B) -> Type
is-associative {A} {B} {C} _+_ _++_ = (a : A) (b : B) (c : C) -> a + (b ++ c) == (a + b) ++ c`

(sorry my Markdown skills are lacking). Note how this definition works for a single operations associativity, but also the associativity one need in e.g. a bimodule or an algebra over a ring.

**Comment by mortberg** [comment]
> What would be nice is that Agda supported record syntax for defining iterated Sigma types, so that, in particular, we automatically had names for the projections.

Yes, but I don't know how that would help with efficiency. When working with more complicated nested structures we've noticed that using `no-eta-equality` in the Record definitions for algebraic structures helps a lot with efficiency. I'm not sure if this can be achieved for nested Sigmas as we generally want eta for Sigma.

**Comment by mortberg** [comment]
> Record types and nested Σ-types are not equivalent: it is often easier for Agda to infer the values of implicit arguments when record types are used.

By "not equivalent" I guess you don't mean "equivalent" like we do in the univalent mathematics? Anyway this sounds like yet another argument for developing the theory about various structures using Records instead of nested Sigmas.
 
> A problem with the standard library's algebraic hierarchy was recently noticed: the definition of at least one ring-like structure does not require that the setoids underlying the additive and multiplicative monoids are equal. However, this is not an issue if you always use equality.

Right, a lot of things get more natural when only using equality/paths.

**Comment by mortberg** [comment]
> One difference I would make from the standard library (which I did not work on, I should say), is to make generic definitions for the various properties (associativity, commutativity, distributivity etc.) so that one could for example say
> `assoc : _+_ is-associative`
> for example. But also, to make sure these definitions are generic as possible to accomodate modules and multi-sorted algebraic theories generally. For example, instead of doing associativity for a single operation, we could do it for two operations
> 
> `is-associative : {A B C : Type} (_+_ : A -> B -> B) (_++_ : B -> C -> B) -> Type is-associative {A} {B} {C} _+_ _++_ = (a : A) (b : B) (c : C) -> a + (b ++ c) == (a + b) ++ c`
> 
> (sorry my Markdown skills are lacking). Note how this definition works for a single operations associativity, but also the associativity one need in e.g. a bimodule or an algebra over a ring.

Yeah, I'm planning to add something similar to what's in the standard library for widely used properties like this. I'm not sure if I want to make them as general as you're suggesting though... Maybe I'm old-fashioned but I don't really like to think of scalar multiplication as associativity. :-)

**Comment by martinescardo** [comment]
There are lots of theorems about Sigma in univalent mathematics. We have to reprove all of them each time we use a single record. In particular regarding SIP, but not only. Efficiency of type checking is one dimension. An orthogonal one is efficiency of the mathematical development. I use Sigma and I would like to have better support for Sigma. People who want to use records can still use records. I just would like a definition with the keyword "Sigma" (say) that otherwise was like the record definition, but produced an iterated binary Sigma type with synonyms for the projections.

**Comment by Saizan** [comment]
> There are lots of theorems about Sigma in univalent mathematics. We have to reprove all of them each time we use a single record. 

It is very easy to prove a record type is equivalent to a nested sigma type, which should make the lemmas about sigmas available where you need them.

**Comment by martinescardo** [comment]
I don't want to do this for each record type.

**Comment by martinescardo** [comment]
It just clutters the code and makes the maths unreadable.

**Comment by guillaumebrunerie** [comment]
> I don't want to do this for each record type.

It shouldn’t be too difficult to do it automatically using reflection. Hasn’t someone done it already?

**Comment by mortberg** [comment]
I've started rewriting the Semigroup file the way I'm suggesting that all algebraic structures should be done now: https://github.com/agda/cubical/pull/360

The idea is to define semigroups using records as in the standard library and only use the Sigma version to prove that the axioms form a prop and for characterizing the equality of semigroups using the SIP. I then transport these two results over to the record version. There's some boilerplate code for this transport and I wonder if someone can see a way to do it easier (without relying on any fancy automation)? I want to have the manual proofs as streamlined as possible before trying to automate things. (I'm not yet using @ecavallo 's fancy macros for the SIP, but maybe they will help with getting rid of boilerplate code?)

Once we have the semigroups worked out I think we should do similar changes to all other algebraic structures in the library.

**Comment by pnlph** [comment]
Is it feasible to have both records and sigma declaration of each definitions like @martinescardo proposes? Or is it better to define only one and rely on a kind of transport between records and sigma types so the users may get the other "on demand"?

I would like to be able to visualize better the difference, could someone please post for instance the Sigma equivalent to the record `Iso` or any other use case? I still do not understand the consequences of the orthogonality between the typechecking and the mathematical efficiency.
```agda
record Iso {ℓ ℓ'} (A : Type ℓ) (B : Type ℓ') : Type (ℓ-max ℓ ℓ') where
  constructor iso
  field
    fun : A → B
    inv : B → A
    rightInv : section fun inv
    leftInv : retract fun inv
```

**Comment by mortberg** [comment]
> Is it feasible to have both records and sigma declaration of each definitions like @martinescardo proposes? Or is it better to define only one and rely on a kind of transport between records and sigma types so the users may get the other "on demand"?

I've been experimenting with this for semigroups here: https://github.com/agda/cubical/pull/360

It's not too bad, but some boilerplate code is needed. We can probably automate some of it, but for now I want to make sure that everything is as mathematically simple as possible so I'll just do it explicitly. 

I don't think anything would be gained by writing `Iso` as a nested Sigma. To me this is more of a question about how to organize an algebraic hierarchy (monoids, groups, rings, categories...) to maximize readability of goals and efficiency.

**Comment by mortberg** [comment]
I've now rewritten semigroups and monoids the way I suggest in this thread: https://github.com/agda/cubical/blob/master/Cubical/Structures/Monoid.agda

About 70 LOC are needed to transport the fact that the monoid axioms form an h-prop and the SIP for monoids from the Sigma to the record version. I don't think this is too bad and as I can delete all of the boilerplate code related to the syntax modules the files are not really any longer. I'll do the same change for rings next and see how that goes.

**Comment by mortberg** [comment]
I've now rewritten Group, AbGroup, Ring and CommRing in Structures this way as well: https://github.com/agda/cubical/pull/364

The boilerplate and overhead for relating the Sigma version of these structures to the record version was smaller than I expected and except for groups it was pretty much just copy-paste. When fixing the theory about these structures I found that the record versions were a lot nicer to work with than the nested Sigma types, so I'm happy I took the time to do this tedious rewrite. I'll close this issue once the PR is merged.

**Comment by mortberg** [comment]
> > Personally I don't see that much of a problem in working with nested sigma types. I think it is better to keep a low-level definition to be able to easily use results like the SIP. Then one can define a module as a higher-level interface to be able to use the structure in a similar manner to a record type.
> > See for example GroupLemmas in https://github.com/Edlyr/cubical/blob/master/Cubical/Structures/Group/Properties.agda#L8
> 
> One reason that I don't like nested Sigma types is that they reduce readability of goals a lot. For instance when working on matrices I was asked to prove the following type of goals:
> 
> ```
> Goal: (x y z : FinMatrix ⟨ R ⟩ n n) →
>       snd (snd raw-ring-structure-FinMatrix) x
>       (fst raw-ring-structure-FinMatrix y z)
>       ≡
>       fst raw-ring-structure-FinMatrix
>       (snd (snd raw-ring-structure-FinMatrix) x y)
>       (snd (snd raw-ring-structure-FinMatrix) x z)
> ```
> 

Btw, this goal now looks like:

```
Goal: (x y z : FinMatrix R n n) →
      mulFinMatrix x (addFinMatrix y z) ≡
      addFinMatrix (mulFinMatrix x y) (mulFinMatrix x z)
```

Quite an improvement.
