### ISSUE TITLE
The color scheme fail to indicate that types don't check

### ISSUE THREAD

**Issue by 3abc** [agda/cubical#35]
For the following code, the type doesn't check but the color scheme makes it look like checked.

```
{-# OPTIONS --cubical #-}
open import Cubical.Core.Prelude
open import Cubical.Basics.Nat

Nat-test : ℕ → ℕ
Nat-test 0 = 0
Nat-test (suc n) = suc n

Nat-test-id : (Nat-test ≡ (\ x → x))
Nat-test-id i x = x
-- Nat-test-id i 0 = 0
-- Nat-test-id i (suc n) = suc n
```

Agda complains 
`Nat-test x != x of type ℕ when checking the definition of Nat-test-id`

But what I got on screen was the following (so the color "checks", type doesn't):

![image](https://user-images.githubusercontent.com/46010137/51811740-3fdc0000-2263-11e9-9c31-15cf203f71da.png)

I'm not sure if this is an issue of Agda or Cubical (or simply due to something silly for this particular color scheme, I'm using the default one). But if I do similar things in Agda without `--cubical` it does complain with color:

![image](https://user-images.githubusercontent.com/46010137/51811986-749c8700-2264-11e9-8582-0685895713a9.png)

-----------

On a side note, I wish 

```
Nat-test-id : (Nat-test ≡ (\ x → x))
Nat-test-id i x = x
```

just checks. (Why doesn't it? Just because `Nat-test` was defined by pattern matching?)

**Comment by mortberg** [comment]
Should we move this issue over to Agda?

**Comment by Saizan** [comment]
Currently Agda will highlight the declared ```Nat-test-id```, feel free to reopen an issue about this on the ```agda``` repository if it's still a problem though.
