### ISSUE TITLE
Add cubical agda paper

### ISSUE THREAD

**Issue by pnlph** [agda/cubical#366]
I open this issue to add the cubical agda paper as requested in #353 . Is this the right one?

> Cubical agda: a dependently typed programming language with univalence and higher inductive types
> https://dl.acm.org/doi/10.1145/3341691

You can assign me the issue.

**Comment by mortberg** [comment]
Yup, that's the one

**Comment by ice1000** [comment]
Is this done? Shall we close this issue?

**Comment by ecavallo** [comment]
We have decided not to add more to the Papers folder.
