### ISSUE TITLE
Redefine isoToEquiv?

### ISSUE THREAD

**Issue by mortberg** [agda/cubical#372]
We could redefine isoToEquiv as follows:

```
isoToEquiv : (f : A → B) (g : B → A) → ((b : B) → f (g b) ≡ b) → ((a : A) → g (f a) ≡ a) → A ≃ B
isoToEquiv {A = A} {B = B} f g fg gf = f , isoToIsEquiv i
  where
  i : Iso A B
  Iso.fun i      = f
  Iso.inv i      = g
  Iso.rightInv i = fg
  Iso.leftInv i  = gf
```

That way it would be a bit nicer to use and there would be no risk of isos not being defined using copatterns.

**Comment by mortberg** [comment]
This turned out to make the code less readable with no speedup: https://github.com/agda/cubical/pull/442

**Comment by Saizan** [comment]
A generic definition like that doesn't actually help because internally `i` will be lambda-lifted so the arguments to `isoToEquiv` will appear as the arguments of `i`, making it not any more efficient than the `iso` constructor itself.

**Comment by mortberg** [comment]
> A generic definition like that doesn't actually help because internally `i` will be lambda-lifted so the arguments to `isoToEquiv` will appear as the arguments of `i`, making it not any more efficient than the `iso` constructor itself.

Oh! I wonder if that affects many other definitions which we believe to be optimized by copatterns? (@aljungstrom )
