### ISSUE TITLE
Script for getting timings for typechecking files

### ISSUE THREAD

**Issue by mortberg** [agda/cubical#375]
I would love to have a script that runs `time` on each file when typechecking and then show the N slowest. More fine grained data would also be useful (like which are the slowest definitions to check in these files), but a simple script would be enough to keep track of which files are the slowest.

**Comment by cangiuli** [comment]
We can add the following to the Makefile (I can open a PR):

```
.PHONY : timings
timings: clean
	$(AGDA) -v profile.modules:10 Cubical/README.agda
```

This causes Agda to check the entire library and then output the following:

```
Total                                           275,643ms 
Miscellaneous                                     3,518ms 
Cubical.ZCohomology.Groups.Sn                    26,112ms 
Cubical.ZCohomology.KcompPrelims                 19,645ms 
Cubical.ZCohomology.Groups.Wedge                  7,493ms 
Cubical.ZCohomology.Properties                    6,763ms 
Cubical.Data.DescendingList.Examples              6,420ms 
Cubical.ZCohomology.MayerVietorisUnreduced        5,956ms 
  [ ... ]
```

Relatedly, why does `make check` invoke Agda once for each import of `Cubical/README.agda` instead of just checking that file? Am I missing something?

**Comment by mortberg** [comment]
Wow, I didn't know Agda already had this built in. This should help @aljungstrom with speeding up the cohomology computations further. Please make a PR!

I think `make check` does this in order to make sure that we're not missing something if we forget to add some Everything file to the README. It might be better if Travis would check that the README is complete though.
