### ISSUE TITLE
Naming convention for algebra related code

### ISSUE THREAD

**Issue by mortberg** [agda/cubical#403]
It would be nice if all the algebra would be using some more consistent naming schema. Here's a suggestion that we are more or less following:

- First letter of structure names and types should be uppercase (like `Ring`)
- Use appropriate abbreviation: 
  - Comm = commutative
  - Assoc = associative
  - DistR/DistL = distribute right/left
- Use camelCase as much as possible, also for properties/lemmas related to operations. For example
  - `+Assoc`
  - `·DistR+`

I'm not sure about how to name lemmas like these: https://github.com/agda/cubical/blob/master/Cubical/Structures/Ring.agda#L272

This should be implemented after https://github.com/agda/cubical/pull/401

**Comment by mchristianl** [comment]
Would it be "safe" to rename every occurrence of `_*_` to `_·_` in the `Cubical/Algebra` subdirectory?

**Comment by mortberg** [comment]
> Would it be "safe" to rename every occurrence of `_*_` to `_·_` in the `Cubical/Algebra` subdirectory?

Sure! I think this should be the name for multiplication of numbers as well

**Comment by mortberg** [comment]
(just to be clear, it's \cdot not \.)

**Comment by mchristianl** [comment]
The `*` is currently used in

- **Algebra/CommRing**
- **Data/BinNat** (just a comment)
- **Data/Fin**
- **Data/InfNat**
- **Data/Nat**
- **Data/NatPlusOne**
- Data/Sigma
- Data/Unit
- (Data/Vec)
- HITs/AssocList
- [HITs/Colimit ("lower star functor" should remain `*`)](https://github.com/agda/cubical/blob/367dd3d4cf185693f02aac3deef93888dedc7eeb/Cubical/HITs/Colimit/Base.agda#L38)
- HITs/FiniteMultiset
- (HITs/Hopf)
- **HITs/Ints/BiInvInt**
- **HITs/Ints/QuoInt**
- HITs/ListedFiniteSet
- (HITs/Rationals/HITQ)
- **HITs/Rationals/QuoQ**
- **HITs/Rationals/SigmaQ**
- HITs/RPn
- [HITs/S1 (debatable)](https://github.com/agda/cubical/blob/367dd3d4cf185693f02aac3deef93888dedc7eeb/Cubical/HITs/S1/Base.agda#L396)
- HITs/Truncation
- HITs/Truncation/FromNegTwo
- Homotopy/Connected
- Modalities/Modality
- (Papers/Synthetic)
- Structures/Auto
- Structures/Relational/Auto
- ZCohomology/MayerVietorisUnreduced

Where I would replace it with `\cdot` in the **fat** marked parts. What about [HITs/S1](https://github.com/agda/cubical/blob/367dd3d4cf185693f02aac3deef93888dedc7eeb/Cubical/HITs/S1/Base.agda#L396)?

**Comment by mortberg** [comment]
I agree with all the fat marked parts. For the circle I think it's bad style that there is a definition `rot` which is then renamed to an operator. There should only be one of these, so please open another issue about this and leave it as it is for now.

**Comment by mortberg** [comment]
Leaving this open for now, but should be fixed very soon by
