### ISSUE TITLE
Almost rings without boilerplate

### ISSUE THREAD

**Issue by felixwellen** [agda/cubical#407]
The ring solver of @oisdk uses a structure called 'AlmostRing'. I would like to add that (and probably SemiRing) to our structures in 'Algebra' as a part of #297. However, it might be a good Idea to leave the boilerplate for SIP out unless we need it. I think we already have a heavy burden on refactoring SIP things and we also have enough examples to test refactorings.

**Comment by felixwellen** [comment]
(ping @mortberg @mzeuner @ecavallo )

**Comment by mortberg** [comment]
Yeah, I agree with this. I don't know what an "AlmostRing" is, but it sounds like something that doesn't occur in nature. SemiRings might be useful to have, but when experimenting with writing a ring solver I don't think you should spend any time on SIP boilerplate code unless you need it. The best is probably if all the code related to the ring solver go in Algebra.RingSolver and if someone needs SemiRing in the meantime they can move it and add the SIP boilerplate code

**Comment by felixwellen** [comment]
Good. I'll start with that then.

**Comment by mortberg** [comment]
Perfect! Closing this issue
