### ISSUE TITLE
Any interest in W or Integer properties?

### ISSUE THREAD

**Issue by glguy** [agda/cubical#419]
I've been working on some things as learning exercises. If any of it is worth cleaning up and submitting as a PR please let me know. If not feel free to close this issue.

Properties of W-types, primarily their HLevels

https://glguy.net/share/agda/W.html

Properties of DiffInt integers: addition, negation, absolute value, ordering relation. There's already a bunch of different work on integers in the library so this might not be interesting.

https://glguy.net/share/agda/DiffInt.html

**Comment by mortberg** [comment]
Yes! I would love to see the W types code as a PR. The DiffInt code should also be interesting, so please open a separate PR for it.

**Comment by ecavallo** [comment]
Feel free to open a PR sometime. Closing this issue for now.
