### ISSUE TITLE
Make level arguments to types with structure explicit

### ISSUE THREAD

**Issue by ecavallo** [agda/cubical#444]
Types like `Monoid {ℓ}`, `Group {ℓ}` almost always need the level variable given explicitly, so we may as well make the arguments explicit. I think we made the level argument to `TypeOfHLevel` explicit for the same reason a while back.

**Comment by mortberg** [comment]
I was thinking the same when fiddling with my PR yesterday. This should be pretty easy to implement

**Comment by ecavallo** [comment]
Resolved by #559
