### ISSUE TITLE
rot as an operator (Cubical.HITs.S1.Base)

### ISSUE THREAD

**Issue by mchristianl** [agda/cubical#453]
In `Cubical.HITs.S1.Base` we have that the definition `rot` occurs again renamed to an operator `_*_`:

https://github.com/agda/cubical/blob/367dd3d4cf185693f02aac3deef93888dedc7eeb/Cubical/HITs/S1/Base.agda#L392-L399

There might be only one of these definitions. Could one of the authors @mortberg @loic-p please give a hint which one to use and whether to keep `*` for the operator or change it to `·` (`which is \cdot`) as [will be common](https://github.com/agda/cubical/pull/450) for the algebraic part of the cubical standard library?

see #403

**Comment by mortberg** [comment]
I think we can change it to `·`. I'm not sure what to do about lemmas named `rot` though, I guess we can keep them as is if we leave a comment that `·` used to be called `rot`?

Btw, this map is called `μ` in the HoTT book so that could also be an option

**Comment by loic-p** [comment]
I agree about changing it to `·`. 
If I remember correctly, `*` was defined because it looks cleaner in formulas, but `rot` was kept since several other lemmas are named after it and I was too lazy to think of a good multiplication-based naming convention :)

**Comment by mortberg** [comment]
Alright, I think we have a conclusion! @mchristianl will you implement it as part of the multiplication renaming PR

**Comment by mchristianl** [comment]
Yes. I've added a commit to the PR. Do we want to keep the `rot` or also rename all the Lemmas?

https://github.com/mchristianl/cubical/commit/f6095542f647a689acad438978686a9a9e309f88#r43369592

I am not familiar with the topic and cannot guess how important the wording "rot" is itself or whether it can just disappear at all.

**Comment by mortberg** [comment]
`rot` stands for rotation and the intuition is that this is like complex multiplication of point on the unit circle. Let's leave `rot` in lemmas and add a comment that _\cdot_ used to be called `rot` and that this name still occurs in lemmas
