### ISSUE TITLE
A way to block term expansion of rec2 in normalization for SetQuotients

### ISSUE THREAD

**Issue by mchristianl** [agda/cubical#456]
Hi,

I am experiencing an issue with large normal forms for expressions involving operations that are defined via `rec2` from `Cubical.HITs.SetQuotients`.

```agda
open import Cubical.Data.Sigma
open import Cubical.Data.Bool
open import Cubical.Data.Nat using (ℕ) renaming (_·_ to _·ⁿ_)
open import Cubical.HITs.Rationals.QuoQ using (ℚ) renaming (_+_ to _+ʳ_)
open import Cubical.HITs.Ints.QuoInt using (ℤ; sign; signed; abs) renaming (_+_ to _+ᶻ_)
open import Cubical.Data.NatPlusOne using (ℕ₊₁; 1+_)
```

For example we have that `_+_` from `Cubical.HITs.Ints.QuoInt` normalizes just "fine"  since it is given a direct definition by pattern-matching (and not via `SetQuotient`):

```agda
test1 : ℤ → _
test1 x = {! x +ᶻ x  !}
-- Normal form:
--   x +ᶻ x
```

Now, on `Cubical.HITs.Rationals.QuoQ` when we apply `_+_` to a `ℤ × ℕ₊₁` representation of `ℚ`, this also gives a "useful" result:

```agda
test2 : ℤ × ℕ₊₁  → _
test2 x = {! [ x ] +ʳ [ x ]  !}
-- Normal form:
--   [  signed (sign (fst x) ⊕ false) (abs (fst x) ·ⁿ suc (ℕ₊₁.n (snd x)))
--   +ᶻ signed (sign (fst x) ⊕ false) (abs (fst x) ·ⁿ suc (ℕ₊₁.n (snd x)))
--   , (1+ (ℕ₊₁.n (snd x) +ⁿ ℕ₊₁.n (snd x) ·ⁿ suc (ℕ₊₁.n (snd x))))
--   ]
```

But if one starts to prove theorems with a mixed application, the normalized term for `_+_` explodes:

```agda
test3 : ℚ → ℤ × ℕ₊₁  → _
test3 x y = {! x +ʳ [ y ]  !}
-- Normal form:
--   rec
--   (λ f g F G i j z →
--      squash/ (f z) (g z) (λ i₁ → F i₁ z) (λ i₁ → G i₁ z) i j)
--   (λ a → ...
--     ...
--   ... 2000 more lines ...
```

Is it somehow possible to re-define `_+_` on `ℚ`, or more generally, to define an operation with `rec2`, in a way that it does not expand the whole definition of `rec2` when normalizing? Though it should still normalize further, when a "useful" normalization (in terms of the underlying operation on the set quotient's representation within `rec2`) is available. (wishful thinking)

**Comment by mortberg** [comment]
I'm surprised this is so big... @Saizan is the path constructor endpoint correction being performed in `transp` for truncations? Maybe we only optimized this for HITs without parameters?

**Comment by Saizan** [comment]
The problem is that since `rec` is stuck on the match on `x` it does not reduce further, so normalization goes and normalizes all the arguments instead.

We do not do anything special for transp for truncations because we never figured out a general thing to do. I do not think the normal form would be smaller here if we did though.

> Is it somehow possible to re-define _+_ on ℚ, or more generally, to define an operation with rec2, in a way that it does not 
> expand the whole definition of rec2 when normalizing? Though it should still normalize further, when a "useful" 
> normalization (in terms of the underlying operation on the set quotient's representation within rec2) is available. (wishful thinking)

I wonder if reflection is expressive enough to do this with a macro: take the arguments for `rec2` and generate a function definition that recurses directly, and maybe also a proof that the function is path equal to the rec2 call.

Or maybe something could be done with the new `onlyReduce*` primitives added to reflection?

A quick hack would be to define your own wrapper for `_+ʳ_`, i.e. a new function that directly matches on both arguments and then calls `_+ʳ_` on them.

**Comment by mchristianl** [comment]
> A quick hack would be to define your own wrapper for _+ʳ_, i.e. a new function that directly matches on both arguments and then calls _+ʳ_ on them.

@Saizan I tried to directly reformulate `rec2` in that way but I cannot get my head around the last case with the double-`squash/`es:

```agda
rec2' : {B : Type ℓ} (Bset : isSet B)
      → (f : A → A → B)
      → (feql : (a b c : A) (r : R a b) → f a c ≡ f b c)
      → (feqr : (a b c : A) (r : R b c) → f a b ≡ f a c)
      → A / R → A / R → B
rec2' Bset f feql feqr x@([ _ ])                     y@([ _ ])                     = rec2 Bset f feql feqr x y
rec2' Bset f feql feqr x@([ _ ])                     y@(eq/ _ _ _ _)               = rec2 Bset f feql feqr x y
rec2' Bset f feql feqr x@(eq/ _ _ _ _)               y@([ _ ])                     = rec2 Bset f feql feqr x y
rec2' Bset f feql feqr x@(eq/ _ _ _ _)               y@(eq/ _ _ _ _)               = rec2 Bset f feql feqr x y
rec2' Bset f feql feqr x@(squash/ a₁ b₁ p₁ q₁ i₁ j₁) y@([ _ ])                     = let g₁ = λ x → rec2' Bset f feql feqr x y in Bset (g₁ a₁) (g₁ b₁) (cong g₁ p₁) (cong g₁ q₁) i₁ j₁
rec2' Bset f feql feqr x@(squash/ a₁ b₁ p₁ q₁ i₁ j₁) y@(eq/ _ _ _ _)               = let g₁ = λ x → rec2' Bset f feql feqr x y in Bset (g₁ a₁) (g₁ b₁) (cong g₁ p₁) (cong g₁ q₁) i₁ j₁
rec2' Bset f feql feqr x@([ _ ])                     y@(squash/ a₂ b₂ p₂ q₂ i₂ j₂) = let g₂ = λ y → rec2' Bset f feql feqr x y in Bset (g₂ a₂) (g₂ b₂) (cong g₂ p₂) (cong g₂ q₂) i₂ j₂
rec2' Bset f feql feqr x@(eq/ _ _ _ _)               y@(squash/ a₂ b₂ p₂ q₂ i₂ j₂) = let g₂ = λ y → rec2' Bset f feql feqr x y in Bset (g₂ a₂) (g₂ b₂) (cong g₂ p₂) (cong g₂ q₂) i₂ j₂
rec2' Bset f feql feqr x@(squash/ a₁ b₁ p₁ q₁ i₁ j₁) y@(squash/ a₂ b₂ p₂ q₂ i₂ j₂) = {!   !}
```

If it is possible to implement that case, would you have any hints for me on how to understand and derive such an implementation?

```
Goal B
———— Boundary ——————————————————————————————————————————————
i₁ = i0 ⊢ rec2' Bset f feql feqr (p₁ j₁)                     (squash/ a₂ b₂ p₂ q₂ i₂ j₂)
i₁ = i1 ⊢ rec2' Bset f feql feqr (q₁ j₁)                     (squash/ a₂ b₂ p₂ q₂ i₂ j₂)
j₁ = i0 ⊢ rec2' Bset f feql feqr  a₁                         (squash/ a₂ b₂ p₂ q₂ i₂ j₂)
j₁ = i1 ⊢ rec2' Bset f feql feqr  b₁                         (squash/ a₂ b₂ p₂ q₂ i₂ j₂)
i₂ = i0 ⊢ rec2' Bset f feql feqr (squash/ a₁ b₁ p₁ q₁ i₁ j₁) (p₂ j₂)
i₂ = i1 ⊢ rec2' Bset f feql feqr (squash/ a₁ b₁ p₁ q₁ i₁ j₁) (q₂ j₂)
j₂ = i0 ⊢ rec2' Bset f feql feqr (squash/ a₁ b₁ p₁ q₁ i₁ j₁)  a₂
j₂ = i1 ⊢ rec2' Bset f feql feqr (squash/ a₁ b₁ p₁ q₁ i₁ j₁)  b₂
```

**Comment by Saizan** [comment]
Before you go through, are the normal forms actually improved much by using this `rec2'` ? It seems that a lot of the ugliness would still be there. You do skip the `isSet\Pi` construction though, that's nice.

Anyhow I would also not do a double squash case, I would only have the following two cases, they both should easily follow from Bset:

```agda
rec2' Bset f feql feqr x@(squash/ a₁ b₁ p₁ q₁ i₁ j₁)  y                                          = ?
rec2' Bset f feql feqr x                                           y@(squash/ a₂ b₂ p₂ q₂ i₂ j₂) = ?
```

**Comment by mortberg** [comment]
If you don't want to pattern match that deep you can probably get some inspiration from the following code I recently wrote: https://github.com/agda/cubical/blob/master/Cubical/HITs/SetTruncation/Properties.agda#L31

**Comment by mchristianl** [comment]
> It seems that a lot of the ugliness would still be there.

@Saizan of course, you are right this does expand all the arguments of `rec2'` - especially `Bset` which causes the long normal form. I've checked this on a wrapper on `_+ʳ_` where your suggestion is working as expected and fooled myself with assuming that `rec2` behaves the same.

So this wrapper indeed is a hack/idiom necessary on every definition making use of `rec2` which might be automated by a macro generating the clauses.

> If you don't want to pattern match that deep you can probably get some inspiration from the following code I recently wrote

@Saizan @mortberg Thank you for your hints! I made an example on `Cubical.Data.DiffInt` which is defined like

```agda
rel : (ℕ × ℕ) → (ℕ × ℕ) → Type₀
rel (a₀ , b₀) (a₁ , b₁) = a₀ + b₁ ≡ a₁ + b₀

ℤ = (ℕ × ℕ) / rel
```
and we have that wrapping `_+'_` in the following way

```agda
_+'_ : (a b : ℕ × ℕ) → ℤ
(a⁺ , a⁻) +' (b⁺ , b⁻) = [ a⁺ +ⁿ b⁺ , a⁻ +ⁿ b⁻ ]

+-respects-relʳ : (a b c : ℕ × ℕ) → rel a b → (a +' c) ≡ (b +' c)
...

+-respects-relˡ : (a b c : ℕ × ℕ) → rel b c → (a +' b) ≡ (a +' c)
...

_+''_ : ℤ → ℤ → ℤ
_+''_ = rec2 {R = rel} {B = ℤ} φ _+'_ +-respects-relʳ +-respects-relˡ
  where abstract φ = isSetℤ

_+_ : ℤ → ℤ → ℤ
x@([ _ ])               + y@([ _ ])               = x +'' y
x@([ _ ])               + y@(eq/ _ _ _ _)         = x +'' y
x@(eq/ _ _ _ _)         + y@([ _ ])               = x +'' y
x@(eq/ _ _ _ _)         + y@(eq/ _ _ _ _)         = x +'' y
x@(eq/ _ _ _ _)         + y@(squash/ a b p q i j) = isSetℤ _ _ (cong (x +_) p) (cong (x +_) q) i j
x@([ _ ])               + y@(squash/ a b p q i j) = isSetℤ _ _ (cong (x +_) p) (cong (x +_) q) i j
x@(squash/ a b p q i j) + y                       = isSetℤ _ _ (cong (_+ y) p) (cong (_+ y) q) i j
```

behaves nicely:

```agda
test1 : ℤ → _
test1 x = {! x + x  !}
-- Normal form
--   x + x    ☺

test2 : ℕ × ℕ → _
test2 x@(a , b) = {! [ x ] + [ x ]  !}
-- Normal form
--   [ a +ⁿ a , b +ⁿ b ]     ☺

test3 : ℤ → ℕ × ℕ → _
test3 x y@(a , b) = {! x + [ y ]  !}
-- Normal form
--   x + [ a , b ]     ☺
```

and it does not look too bad. At least temporarily for proving theorems about `_+_`.

A similar consideration should hold for `_+_` from `Cubical.HITs.Ints.QuoInt`.
