### ISSUE TITLE
Proof of `Fin (m + n) ≡ (Fin m) ⊎ (Fin n)`

### ISSUE THREAD

**Issue by ayberkt** [agda/cubical#468]
While working on something, I had to write down a proof of this fact as I couldn't find it in `cubical`. It's possible that it is here and I failed to find it. If that's not the case though, I can send a PR with it.

**Comment by mortberg** [comment]
I don't think it is anywhere and it would be nice to have. So please make a PR!

**Comment by ayberkt** [comment]
Also, here are some more related things:

  1. I noticed @jorge-jbs did some work on `FinSet`. Using this, it will now be easy to show that the union of two finite sets is finite so it might be a good idea to add that there;
  1. In fact, I needed this proof when formalising [Kuratowski-finiteness][0] so if you think it would be a good idea to have that, I can make a PR containing that stuff as well.

[0]: https://ncatlab.org/nlab/show/finite+set#Constructivist

**Comment by ayberkt** [comment]
By the way, let me note here that there is a very nice proof of `Fin (m + n) ≡ (Fin m) ⊎ (Fin n)` by @martinescardo in the [`ArithmeticViaEquivalence`](https://www.cs.bham.ac.uk/~mhe/agda-new/ArithmeticViaEquivalence.html) module of his [`TypeTopology`](https://github.com/martinescardo/TypeTopology) development.

I don't have the time to port this to Cubical Agda at the moment but I would encourage someone to do it.
