### ISSUE TITLE
Feature request: pattern matching on identity path

### ISSUE THREAD

**Issue by martinescardo** [agda/cubical#51]
It would be very nice to have cubical Agda to internally translate pattern matching on refl (with --without-K) to path induction. This would not only make proofs more readable, but also would allow existing Agda developments to migrate seamlessly to cubical Agda.

In particular, I am eager to try my own existing development with cubical Agda. I deliberately designed it so that all "univalent" features are explicit assumptions (univalence, functional extensionality, propositional truncation, and everything).

However, because my developement doesn't use J, I can't just supply such assumptions as data and test the computational behaviour of cubical Agda. Because my codebase has 30k lines, it is not an option to just manually convert all uses of pattern matching on refl to uses of J.

In principle we know the theory to convert the use of pattern matching to eliminators automatically, at least if one uses --exact-split, which I do. Moreover, I take care of making definitions in Agda so that I know that they are more or less directly translatable in an automatic way to Martin-Loef combinators.

It should be possible to translate "well behaved code" that relies on without-K-pattern-matching-on-refl to cubicaltt combinators automatically internally in Agda in a transparent way.

**Comment by martinescardo** [comment]
There are 1252 uses of refl (counted with "cat *agda | grep -c refl") and so it is not an option to replace all of those which happen to be patterns (the vast majority) by uses of  J (or equivalent cubical machinery). 

I wanted to test the performance of univalence as computed by cubical Agda with my code, but this is preventing me from doing so.

**Comment by mortberg** [comment]
Yes, this would be great to have. But as this is not a feature request for the agda/cubical library but rather for agda maybe we should discuss it in an issue there instead?

**Comment by martinescardo** [comment]
Yes, sorry, I put my request in the wrong cubical compartment! I will make the request there,

**Comment by mortberg** [comment]
@martinescardo Did you make an issue over at Agda? If so I'll close this one

**Comment by martinescardo** [comment]
Not yet, but you can close it. I am trying to finish a paper, and I am late for the extended deadline I got. :-)

**Comment by mortberg** [comment]
Haha ok, please do this after finishing the paper then :-)

**Comment by martinescardo** [comment]
Done. Haven't finished the paper, though. :-)

https://github.com/agda/agda/issues/3551
