### ISSUE TITLE
Redefine isConnected?

### ISSUE THREAD

**Issue by mortberg** [agda/cubical#539]
I conjecture that we can simplify many proofs about n-connected things by changing the definition into:

```
isConnected : (n : HLevel) (A : Type ℓ) → Type ℓ
isConnected n A = hLevelTrunc n A × isProp (hLevelTrunc n A)
```

This is equivalent to the old definition `isContr (hLevelTrunc n A)` but having an `isProp` proof is probably easier to work with as we avoid reasoning about Sigma-types. I also conjecture that we can make the second component abstract everywhere without breaking computations using n-connected things, but I might be wrong. With this definition it should at least be easier to experiment with this. My hope is that we can speed things up in Z-cohomology by making more things abstract (or at least use copatterns everywhere when proving `isConnected`).

As an experiment I reproved `isConnectedPath` using the above definition and it got quite slick:

```
isConnectedPath : (n : HLevel) {A : Type ℓ}
                → isConnected (suc n) A
                → (x y : A) → isConnected n (x ≡ y)
fst (isConnectedPath n connA x y) = PathIdTruncIso n .Iso.fun (connA .snd _ _)
snd (isConnectedPath n connA x y) =
  subst isProp (PathIdTrunc n) (isProp→isSet (connA .snd) _ _)
```

For reference here's the old version: https://github.com/agda/cubical/blob/master/Cubical/Homotopy/Connected.agda#L167

I'm not sure if the old version so long and complicated because it has been optimized for computation or if it's just harder to prove things about `isContr`... 

So what do you think, should we try to change the definition and see if all proofs get shorter and things get faster?

**Comment by ecavallo** [comment]
A similarly slick proof is possible with the current definition:
```
isConnectedPath : ∀ {ℓ} (n : HLevel) {A : Type ℓ}
  → isConnected (suc n) A
  → (a₀ a₁ : A) → isConnected n (a₀ ≡ a₁)
isConnectedPath zero connA a₀ a₁ = isContrUnit*
isConnectedPath (suc n) {A = A} connA a₀ a₁ =
  subst isContr (PathIdTrunc (suc n)) (isContr→isContrPath connA _ _)
```
A more optimized but still short version would use the retract hlevel lemma instead of `subst`:
```
isConnectedPath (suc n) {A = A} connA a₀ a₁ =
  isOfHLevelRetractFromIso 0 (invIso (PathIdTruncIso (suc n))) (isContr→isContrPath connA _ _)
```

**Comment by mortberg** [comment]
Nice! But there's no copatterns so Agda might still try to unfold the equality proof part?  Or maybe `isOfHLevelRetractFromIso` deals with that?

I still think it might be worth separating the point and the path in the definition of `isConnected` so that it's easier to experiment with making the path abstract. Or what do you think? It would be nice to have an example using Freudenthal to test whether we actually need this path to be transparent or if it can be opaque (I think @aljungstrom is going to prepare such a test for us). 

Another remark: the proof of `PathIdTruncIso` is quite scary. Could one try to optimize it? Maybe using glue directly instead of univalence could make a difference... Or maybe someone smart can come up with a better cubical proof.

**Comment by ecavallo** [comment]
I'm not sure what you mean by separating the point and path. The current definition of `isConnected` is already a sigma-type consisting of a point and family of paths.

I don't think there is much one can do about `PathIdTruncIso`.

**Comment by mortberg** [comment]
I guess I just mean that it might be nice to have them even more separate by having an `isInhProp`. Then we can easier experiment with making the path abstract

**Comment by ecavallo** [comment]
I don't understand how that makes abstracting easier. `isContr` is also a pair of things where we could make the second one abstract.
```
isCenter : {A : Type ℓ} → A → Type ℓ
isCenter x = ∀ y → x ≡ y

isContr : Type ℓ → Type ℓ
isContr A = Σ[ x ∈ A ] isCenter x
```
