### ISSUE TITLE
'awaiting review' label

### ISSUE THREAD

**Issue by felixwellen** [agda/cubical#591]
It is not so easy to quickly see, which PRs are drafts and which are awaiting review. And I don't see a way to sort them. So it would be an easy fix to have an 'awaiting review' label like here: https://github.com/leanprover-community/mathlib

**Comment by ecavallo** [comment]
According to https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github/searching-issues-and-pull-requests you can filter by `draft:false` or `draft:true`.

**Comment by felixwellen** [comment]
Thanks ;-) That works well enough for me.
However, I was thinking it might be good to make that distinction jump in every ones face when looking at PRs.

**Comment by felixwellen** [comment]
Anyway, I'll close it.
