### ISSUE TITLE
UnsupportedYet Injectivity

### ISSUE THREAD

**Issue by barrettj12** [agda/cubical#623]
When I try to import `Cubical.Categories.Category.Base`, I get a series of errors like the following:
```
...\Cubical\Data\FinData\Base.agda:37,1-40,24
Could not generate equivalence when splitting on indexed family,
the function will not compute on transports by a path.
  Reason: UnsupportedYet Injectivity
                           position:    0
                           type:        ℕ
                           datatype:    ℕ
                           parameters: 
                           indices:    
                           constructor: suc
when checking the definition of _==_
```
These errors are caused by the following files
- `Data.FinData.Base`
- `Data.Vec.Base`
- `Data.Vec.NAry`
- `Functions.FunExtEquiv`

I am running:
- Windows 10
- the latest development version of Agda (agda/agda@6cb77e1)
- the latest version of the cubical library.

**Comment by Saizan** [comment]
Those are warnings, and are expected until Agda is extended to support those.

**Comment by barrettj12** [comment]
You can use the `-W ignore` flag (inside `{-# OPTIONS  ...  #-}`) to suppress the errors.

**Comment by barrettj12** [comment]
Related: https://github.com/agda/agda/issues/5577

**Comment by barrettj12** [comment]
@Saizan I want to be able to suppress just the `UnsupportedYet Injectivity` and not any others. I found the
`-W no{error-name}`, but I can't work out what `{error-name}` is in this case. Do you know?
