### ISSUE TITLE
Makefile: `runghc` instead of `runhaskell`

### ISSUE THREAD

**Issue by barrettj12** [agda/cubical#633]
To get `make` to run on my Windows 10 machine, I had to change line 5 of GNUmakefile from
```
RUNHASKELL?=runhaskell
```
to
```
RUNHASKELL?=runghc
```
I'm not sure if this is related to Windows, or to new versions of GHC. I'm running GHC version 9.0.1.

Is `runhaskell` still working for those on Unix?

**Comment by mortberg** [comment]
On my Arch Linux machine `runhaskell` is just a script which calls `runghc`, so I would be fine with changing it

**Comment by mortberg** [comment]
Maybe someone with a Mac could check what they have?

**Comment by barrettj12** [comment]
Right, it seems that `runhaskell` is supposed to point towards whatever Haskell compiler you're using. Maybe we should leave it as is, in case anyone would want to use a different Haskell compiler, and I'll just point `runhaskell` to `runghc` on my machine.
