### ISSUE TITLE
Field names in `Data.Graph`

### ISSUE THREAD

**Issue by barrettj12** [agda/cubical#648]
In `Data.Graph.Base`, directed graphs are defined
```agda
record Graph ℓv ℓe : Type (ℓ-suc (ℓ-max ℓv ℓe)) where
  field
    Obj : Type ℓv
    Hom : Obj → Obj → Type ℓe
```
Surely these should be called `Vertex`/`Node` and `Edge` instead?

**Comment by mortberg** [comment]
Good catch! I prefer `Node`/`Edge`
