### ISSUE TITLE
Parse error in 0.3 Primitives

### ISSUE THREAD

**Issue by DavidJaz** [agda/cubical#652]
I'm trying to play the ["HoTT Game"](https://thehottgameguide.readthedocs.io), and this uses cubical-0.3. When trying to load the first file, however, I get a parse error:

`.../cubical-0.3/Cubical/Core/Primitives.agda:37,14: Parse error
Set<ERROR>
    to Type
           ; Setω ...`

which occurs during the renaming of "Set" to "Type". I'm using Agda version 2.6.2-b7da577. I'm confused at what to do here. 

Here's some context for those lines:
```
open import Agda.Primitive public
  using    ( Level )
  renaming ( lzero to ℓ-zero
           ; lsuc  to ℓ-suc
           ; _⊔_   to ℓ-max
           ; Set    to Type
           ; Setω  to Typeω )
open import Agda.Builtin.Sigma public
```

**Comment by DavidJaz** [comment]
I reinstalled Agda and it worked.

**Comment by XinYaanZyoy** [comment]
@DavidJaz can you please provide the versions of Cubical, Agda, Emacs, and TheHoTTGame?

any suggestions to solve the following error?

while "c-c c-l"ing the Quest0.agda, I get the following error,
```
/home/xinyaanzyoy/agdalibs/cubical-0.3/Cubical/Core/Primitives.agda:37,14-14
/home/xinyaanzyoy/agdalibs/cubical-0.3/Cubical/Core/Primitives.agda:37,14: Parse error
Set<ERROR>
   to Type
           ; Setω  ...
```
however, if I comment out everything except the line `module 1FundamentalGroup.Quest0 where`, it loads successfully.

- Agda version v2.6.0.1
- Editor: VS Code (with agda-mode v0.3.7

Attached is the screenshot of libraries path
![image](https://user-images.githubusercontent.com/32465479/147927730-f51859c3-482e-4bb2-8e57-c1fe8c24d4b1.png)

**Comment by leahneukirchen** [comment]
Had the same issue with Agda 2.6.1.3, updating to Agda 2.6.2.1 fixed the problem.
