### ISSUE TITLE
"Not in Scope: R.Telescope at ..../Cubical/Reflection/Base.agda"

### ISSUE THREAD

**Issue by morphismz** [agda/cubical#700]
Hi, I am trying to run the HoTT game. Upon launching first part of the game and trying to load the .agda file, I received the following error message: 
.../agda/cubical/Cubical/Reflection/Base.agda:49,39-50
Not in scope:
  R.Telescope
  at .../agda/cubical/Cubical/Reflection/Base.agda:49,39-50
when scope checking R.Telescope"

The dots are just the path from my home directory.

I then went to load the Base.agda file and received the same error. In emacs, the occurrence of R.Telescope appearing near the end of the file is highlighted in red. It is this appearance: extend*Context : ∀ {ℓ} {A : Type ℓ} → R.Telescope → R.TC A → R.TC A

I'm new to agda and not sure what is causing this problem. Any help would be appreciated.

**Comment by morphismz** [comment]
P.S. Sorry if I did not post this in the right outlet. I'm new around here...

**Comment by xekoukou** [comment]
Update to the  latest agda from the master branch and do the same for cubical.

**Comment by morphismz** [comment]
Ah, thank you. I had used dnf install to install agda. I didn't realize I had 2.6.2 not 2.6.3.
