### ISSUE TITLE
Fix naming scheme for universe levels

### ISSUE THREAD

**Issue by felixwellen** [agda/cubical#769]
I think it would save us some annoyance to fix how we name universe levels. This version is probably the most common:
```agda
 ℓ ℓ' ℓ'' ℓ''' : Level
```
Then - maybe because of me - we have also this version:
```agda
    ℓ ℓ′ ℓ″ ℓ‴ : Level
```
where the hyphons are given by ```\'``` and arrow keys in emacs. Then, there are probably also still ```i j k``` or something like this.
I tend to use the second one, because it is less noisy, but I am good with whatever we decide to use. We should make a choice and write it in CONTRIBUTING.md.

**Comment by ecavallo** [comment]
I've also sometimes used levels with more descriptive labels, especially in code involving many types. For example here: https://github.com/agda/cubical/blob/master/Cubical/Displayed/Sigma.agda.

As for `ℓ'''` vs `ℓ‴`, either is fine to me, but probably `ℓ'''` would be easier in terms of amount of code to rename and ease of find-and-replacing.

**Comment by felixwellen** [comment]
I don't want to throw away documentation, so we could say either meaningful names for universe level, or ```ℓ'''...``` (if we choose that).

**Comment by felixwellen** [comment]
#770
