### ISSUE TITLE
Comments on types of primitives are wrong.

### ISSUE THREAD

**Issue by howsiyu** [agda/cubical#771]
https://github.com/agda/cubical/blob/1b9c97a2140fe96fe636f4c66beedfd7b8096e8f/Cubical/Core/Primitives.agda#L150

Is this comment correct? It seems like `A` in `transp` can vary across universes. E.g.

```agda
forward : {ℓ : I → Level} (A : ∀ i → Type (ℓ i)) (r : I) (u : A r) → A i1
forward A r u = transp (λ i → A (i ∨ r)) r u
```

**Comment by howsiyu** [comment]
https://github.com/agda/cubical/blob/1b9c97a2140fe96fe636f4c66beedfd7b8096e8f/Cubical/Core/Primitives.agda#L92

Not related to the title but it seems like `PartialP`'s return type is `SSet ℓ` instead of `Typeω`?

**Comment by ice1000** [comment]
See #837
