### ISSUE TITLE
Does Algebra naming convention apply to local names?

### ISSUE THREAD

**Issue by thomas-lamiaux** [agda/cubical#812]
Discussing with @felixwellen on #811 , we realized that we didn't understand the naming convention the same way
To me it was supposed to be applied everywhere, for him it is only for global names.

By local / global name I mean the following : 
For instance if someone defines G, 0, +, - then rid+G that would be in a module in Properties is a local name.
Indeed it is later going to be package in a AbGroupStr.
Opposite the one that you get by opening that AbGroupStr is global
(Felix, was that what you meant too ?)

I think this is something that should be specify in NamingAlgebra as it doesn't seem clear.
What is your opinion on the question ?

**Comment by thomas-lamiaux** [comment]
I think that it should applies to all names because :
- This way it is always clear what someone or some function is doing. 
   Even if local names are not meant to be used, one may look at the proof for instance to do something similar.
   This would ease the understanding of the proofs.
- When working with local names, we are often also working with global names. 
I think it would be confusing to mix two conventions in the files.
- There won't be any issue with the global and local names over lapping as once the AbGroupStr is define, the module containing the properties should not be open anymore.
- It is probably easier for people to have a uniform convention ?

**Comment by felixwellen** [comment]
Yes, this is what I meant. 
I would, however, not speak of 'global' names. I guess it makes sense to say, the naming convention should apply to names, that will be used outside a module (I don't know if 'global' is the correct word for that).

It is, of course, always good and recommendable to use names that clearly convey what happens. But I don't think we should put effort into *standardizing* names unless there is a good reason to do it.

**Comment by felixwellen** [comment]
In #811 , I am not confused by the names and I don't see how the standardized names would help me here. To the contrary, it would actually lead to more complicated names, since the operation is called ```·Ab```. Also, if one defines a *specific* structure like this, there might be clashes with the standardized names, one would have to resolve.
In summary, I don't see an advantage of renaming in that case. But I do see an advantage of having the standardized names for the fields of algebraic structures. This was justified by a long series of headaches I and others had in the past.

**Comment by thomas-lamiaux** [comment]
I am going to fix the issue in the algebraic structure soon.

I agree that the notation are not "confusing" here but it still seems clear to have things like `rinvAb` as `·AbInvR`. 
Plus, in a more general case like a ring, algebra or something like that, we are probably going to have different things for 
`·AbDist+L` where the Left is the right of things like that. 

By the way, Dist in NamingAlgebra should be precise in the naming files

**Comment by felixwellen** [comment]
This is too hypothetical for me. I want to focus my regulatory energy on things where I am sure that regulating is needed.

**Comment by thomas-lamiaux** [comment]
> This is too hypothetical for me. I want to focus my regulatory energy on things where I am sure that regulating is needed.
I don't mind spending two days rewriting it in past files if it going to be enforced it new pull request.
The question is more too me if there a reason not to do it.

There is probably more pressing things todo for sure like to it for Algebraic Structures.
But I don't think it should be done like right now but more like in a future, for instance I'll have some time in the summer.

But we could also not do it, your call.

**Comment by thomas-lamiaux** [comment]
However, maybe we should correct those in Highe inductive type, for instance FreeCommMonoid or things like it

**Comment by thomas-lamiaux** [comment]
The other question is what to do with the path constructors ?
https://github.com/agda/cubical/blob/master/Cubical/HITs/FreeGroup/Base.agda#L18
Because if people open them as instances, they will get a definition twice.
