### ISSUE TITLE
Clean up Cubical.Algebra

### ISSUE THREAD

**Issue by felixwellen** [agda/cubical#814]
There are things like Polynomials and Matrix in Cubical.Algebra. We should decide if those things should be moved to subfolders.

**Comment by mortberg** [comment]
Yes, they should :-) We should also merge `Matrix` with `IntegerMatrix`

**Comment by thomas-lamiaux** [comment]
I spoke with Evan was about doing that. If you want I can do it when I am done with this one so probably next week.
I think the #813 will answers about the internal structure of the folders to adopt and so on. 
Maybe here we could discuss about the more general organization of Algebra ?
Like what subfolder to have, identify the problematic files and what to do with them

**Comment by thomas-lamiaux** [comment]
I thought we talked about something like the following ?

#### Algebra/
Matrix/              <= InegerMatrix
Polynomials/

AlgebraicStructure/
- SemiGroup
- Monoid            <= MonoidSolver
- CommMonoid
- Group
- AbGroup         <= DirectSum
- Ring
- CommRing     <= CommRingSolver
- Module
- Algebra
- CommAlgebra

Lattice/
- SemiLattice
- Lattice
- DistLattice

#### Else
NatSolver
ZariskiLattice (I was told by @mzeuner  that it shouldn't be in Lattice)

**Comment by mortberg** [comment]
Will be fixed by https://github.com/agda/cubical/issues/813

Solvers should be moved though, to a new Tactics package
