### ISSUE TITLE
Apply the SIP to fields

### ISSUE THREAD

**Issue by felixwellen** [agda/cubical#820]
Isomorphisms of fields like defined in #797 are not shown to be the same as paths in the type of fields. This can be done analogous to other algebraic structures, e.g. like it is done in ```Cubical/Algebra/Ring/Base.agda```

**Comment by kangrongji** [comment]
Should we extend the notion of `DUARel`? I've had a notion of fields in my own [repo here](https://github.com/kangrongji/cubical-classics/blob/6b7fb3f31579c7e8262ab56cc69c2212d214a5ea/Classical/Algebra/Field/Base.agda#L34), and SIP is easy. The difference is I defined field as a predicate over `CommRing`.

**Comment by felixwellen** [comment]
Having inverses for non-zero elements is a proposition - so it should work as well, or am I missing something?

**Comment by kangrongji** [comment]
Right, just that simple.

**Comment by felixwellen** [comment]
Ah, I guess one point is, that inverses should be moved completely to 'IsField'.

**Comment by kangrongji** [comment]
Yeah, I have realized one difficulty of SIP for fields is, you only have the path if you have well-defined notions of multiplication and multiplicative unit. That means you must have SIP for rings or something first, then lift up it to fields. It's something that seems missing in so far `DUARel` if I don't mistake anything.

**Comment by kangrongji** [comment]
Same thing happened when I was defining ordered ring. I have to write [an ad-hoc brutal-forced argument of SIP for them](https://github.com/kangrongji/cubical-classics/blob/master/Classical/Algebra/OrderedRing/Univalence.agda).

**Comment by felixwellen** [comment]
Hm. So if I have a subtype of some algebraic things, that got some univalence from the DUARel-sutf, I don't get automatically the same for the subtype? Is there no cheap trick to show that field isomorphisms are the same as isomorphisms of the underlying commrings?

**Comment by kangrongji** [comment]
I'm not sure... I haven't really figured out how the whole automation works, better asking @mortberg @ecavallo

**Comment by kangrongji** [comment]
It seems in library "predicate" definition is acceptable as in the case of [monoid](https://github.com/agda/cubical/blob/ce3120d3f8d692847b2744162bcd7a01f0b687eb/Cubical/Algebra/Monoid/Base.agda#L31). Maybe we can do similar things for `Field`?

**Comment by kangrongji** [comment]
Whatever, I've made the alternative definition since it's very simple. See #825. What do you think?

**Comment by kangrongji** [comment]
This issue could be closed now? @felixwellen

**Comment by felixwellen** [comment]
Yes, thanks.
