### ISSUE TITLE
Add univalence as an explicit definition

### ISSUE THREAD

**Issue by gergoerdi** [agda/cubical#9]
There's a comment in `Cubical.Core.Glue` that it contains a proof of univalence:

>  Proof of univalence using that unglue is an equivalence (`EquivContr`)

and then there is a module at the end with

> ```
> EquivContr : ∀ {ℓ} (A : Set ℓ) → isContr (Σ[ T ∈ Set ℓ ] T ≃ A)
>
> module _ {ℓ : I → Level} (P : (i : I) → Set (ℓ i)) where
>   pathToEquiv : A ≃ B
> 
> ```

Do these prove univalence? Do they provide all the kit needed to prove it? I have absolutely no idea. As a regular user, what would be useful is if there was an explicitly spelled out univalence witness:

> ```
> univalence : ∀ {ℓ} {A B : Set ℓ} → (A ≡ B) ≃ (A ≃ B)
> ```

**Comment by Saizan** [comment]
We also have ```ua``` in the same file. But I agree it would be nice to have the proof that ```ua``` is an equivalence.

**Comment by gergoerdi** [comment]
Sure, I wouldn't be surprised if given the above kit and `ua`, the definition of `univalence` is just a one-liner. But it's not obvious to me what that one line would be.

**Comment by mortberg** [comment]
Yes, I totally agree that we should have more standard formulations of univalence (in the Cubical/Basics folder). Felix Wellen is actually already working on this, so we should have it in a not too distant future. 

In the meantime I'll add some comments explaining why this is equivalent to the standard formulation of univalence with a pointer to the right section in the HoTT book.

**Comment by mortberg** [comment]
I added some clarification to the core library now: https://github.com/agda/cubical/commit/063cf7d3cdf751e2eb13f38bc207f44416c8da4c

**Comment by mortberg** [comment]
I came up with a slick proof of the standard formulation now:

https://github.com/agda/cubical/blob/master/Cubical/Basics/Univalence.agda#L56

So closing this issue.

**Comment by martinescardo** [comment]
Can you also add this for the identity type?

**Comment by mortberg** [comment]
Sure @martinescardo ! I'll reopen the issue and do it.

How does this proof compare to other proofs of univalence that you know? I think it is quite slick and it doesn't use uabeta which is something I see as a big plus! (the direct proof of uabeta in cubicaltt relies on how the Kan operations compute which is not very good as it will break if we change the operational semantics...).

**Comment by martinescardo** [comment]
Nice. The proof I have uses Yoneda, but I think it may be "the same" when unfolded. Yoneda itself doesn't rely on *beta, and the *beta part is automatic. http://www.cs.bham.ac.uk/~mhe/agda-new/UF-Yoneda.html#15981

**Comment by mortberg** [comment]
I finished the proof of the more standard formulation of univalence for Id types now: https://github.com/agda/cubical/blob/master/Cubical/Basics/UnivalenceId.agda

**Comment by martinescardo** [comment]
Thanks!
