### ISSUE TITLE
Update Table of Reviewers

### ISSUE THREAD

**Issue by felixwellen** [agda/cubical#942]
Anders:
algebra for Max and synthetic homotopy/cohomology theory for Axel.

how about including our Github handles with our names? 

Felix: 
Another thing: We could updates all the links to use 'Assign' instead of 'Reviewers' - that will improve the overview.

**Comment by mortberg** [comment]
Please use the @ feature so that I don't miss it :-)

Sounds good for Max and Axel. Including Github handles also sounds good!
