### ISSUE TITLE
Data.Bool.and and Data.Bool.or are pattern matching on second argument

### ISSUE THREAD

**Issue by phadej** [agda/cubical#962]
Is there a reason to do that? If not, I'll be happy to make a PR defining

```agda
true  or _ = true
false or x = x
```

etc. which makes proofs about `or` and `and` shorter.

But if there is a good reason, we should add a comment why they are implemented in the way they are.

**Comment by xekoukou** [comment]
I saw that too and changed it in my fork. 

But this raises a more general question : Should our code be determined by the dictatorial rule of definitional equality? For many years, I have tried to use tricks to make agda happy. I consider this a waste of my time.

**Comment by ecavallo** [comment]
I don't think there's any reason for it and no one else has spoken up, so feel free to change it.

**Comment by phadej** [comment]
@ecavallo will do.
