### ISSUE TITLE
`Unknown warning flag: UnsupportedIndexedMatch`

### ISSUE THREAD

**Issue by vezwork** [agda/cubical#982]
I just cloned this repo, added it to my `.agda/libraries`, and added it as a dependency in my project's `agda-lib`. 

In a file `file.agda` I have

```agda
{-# OPTIONS --cubical #-}

module file where

open import Cubical.HITs.FiniteMultiset.Base public
```

and when I load with Agda, I get this error:

```
Unknown warning flag: UnsupportedIndexedMatch. See --help=warning.
when scope checking the declaration
  open import Cubical.HITs.FiniteMultiset.Base public
```

I [looked through this repo and found](https://github.com/agda/agda/blob/3287d7bb105c42550d49dde00fe509ef73d5a369/doc/user-manual/language/cubical.lagda.rst#indexed-inductive-types) that I can use 
```
{-# OPTIONS --cubical -WnoUnsupportedIndexedMatch #-}
```
but then when I load I get another error, now:
```
Unknown warning flag: UnsupportedIndexedMatch. See --help=warning.
```

I'm on MacOS Ventura with an M1 chip, using VSCode, with Agda version 2.6.2.2 installed. I can give more details on my libraries or agda-lib if that is helpful.

**Comment by vezwork** [comment]
I think this may be because I need Agda version 2.6.3 or above. I am attempting to install it. Agda 2.6.2 is the latest version on `brew` for OSX.

**Comment by vezwork** [comment]
I installed Agda using Cabal, which has version 2.6.3 currently. I updated my `agda-mode` extension to use my Cabal installed Agda. Now everything is working! :)

**Comment by vezwork** [comment]
It is confusing because it seems that the latest version of Agda is 2.6.4 but it has not yet made its way to Brew or Cabal.

**Comment by felixwellen** [comment]
Agda 2.6.4 is the current *development* version of Agda. The latest release is 2.6.3 (which might still be in the process of being released).
For anyone with a problem to get Agda 2.6.3: Just checkout the tag v0.4 of this library with
```
git checkout v0.4
```
Then you can use Agda 2.6.2.2. For older versions of Agda, look at the README.md to figure out which tag you can use.
