### ISSUE TITLE
Readme refers to tag: v0.5 for Agda v2.6.3 not such tag exist in repo

### ISSUE THREAD

**Issue by sebeaumont** [agda/cubical#987]
Am I missing something? Is using master with Agda 2.6.3 the workaround?

**Comment by felixwellen** [comment]
They current master is supposed to be the current (unreleased, still changing) state of v0.5.
Maybe adding something like ```v0.5 (current master)``` in the table with the versions makes that clearer?

**Comment by felixwellen** [comment]
Or maybe we also change the sentence above the table to ```Versions as written below, correspond to tags, except for the current development version of cubical, which can be used by checking out master.```
Which is a lot longer, but also pretty clear I guess.

**Comment by sebeaumont** [comment]
Agreed the latter does not refer to a non existent tag, which is unambiguous.

**Comment by felixwellen** [comment]
Should be solved with #1014
